// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AssignTaskArgs {
    pub task_id: String,
    pub agent_id: String,
}

impl From<AssignTaskArgs> for super::Reducer {
    fn from(args: AssignTaskArgs) -> Self {
        Self::AssignTask {
            task_id: args.task_id,
            agent_id: args.agent_id,
        }
    }
}

impl __sdk::InModule for AssignTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `assign_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait assign_task {
    /// Request that the remote module invoke the reducer `assign_task` to run as soon as possible.
    fn assign_task(&self, task_id: String, agent_id: String) -> __sdk::Result<()> {
        self.assign_task_then(task_id, agent_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `assign_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    fn assign_task_then(
        &self,
        task_id: String,
        agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl assign_task for super::RemoteReducers {
    fn assign_task_then(
        &self,
        task_id: String,
        agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AssignTaskArgs {
                task_id,
                agent_id,
            },
            callback,
        )
    }
}
