// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InferenceServer {
    pub server_id: String,
    pub agent_id: String,
    pub provider: String,
    pub base_url: String,
    pub models_json: String,
    pub gpu_vram_mb: u32,
    pub status: String,
    pub current_load: f32,
}

impl __sdk::InModule for InferenceServer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InferenceServer`.
///
/// Provides typed access to columns for query building.
pub struct InferenceServerCols {
    pub server_id: __sdk::__query_builder::Col<InferenceServer, String>,
    pub agent_id: __sdk::__query_builder::Col<InferenceServer, String>,
    pub provider: __sdk::__query_builder::Col<InferenceServer, String>,
    pub base_url: __sdk::__query_builder::Col<InferenceServer, String>,
    pub models_json: __sdk::__query_builder::Col<InferenceServer, String>,
    pub gpu_vram_mb: __sdk::__query_builder::Col<InferenceServer, u32>,
    pub status: __sdk::__query_builder::Col<InferenceServer, String>,
    pub current_load: __sdk::__query_builder::Col<InferenceServer, f32>,
}

impl __sdk::__query_builder::HasCols for InferenceServer {
    type Cols = InferenceServerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InferenceServerCols {
            server_id: __sdk::__query_builder::Col::new(table_name, "server_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            base_url: __sdk::__query_builder::Col::new(table_name, "base_url"),
            models_json: __sdk::__query_builder::Col::new(table_name, "models_json"),
            gpu_vram_mb: __sdk::__query_builder::Col::new(table_name, "gpu_vram_mb"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            current_load: __sdk::__query_builder::Col::new(table_name, "current_load"),
        }
    }
}

/// Indexed column accessor struct for the table `InferenceServer`.
///
/// Provides typed access to indexed columns for query building.
pub struct InferenceServerIxCols {
    pub server_id: __sdk::__query_builder::IxCol<InferenceServer, String>,
}

impl __sdk::__query_builder::HasIxCols for InferenceServer {
    type IxCols = InferenceServerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InferenceServerIxCols {
            server_id: __sdk::__query_builder::IxCol::new(table_name, "server_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InferenceServer {}
