// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inference_server_type::InferenceServer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inference_server`.
///
/// Obtain a handle from the [`InferenceServerTableAccess::inference_server`] method on [`super::RemoteTables`],
/// like `ctx.db.inference_server()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_server().on_insert(...)`.
pub struct InferenceServerTableHandle<'ctx> {
    imp: __sdk::TableHandle<InferenceServer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inference_server`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InferenceServerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InferenceServerTableHandle`], which mediates access to the table `inference_server`.
    fn inference_server(&self) -> InferenceServerTableHandle<'_>;
}

impl InferenceServerTableAccess for super::RemoteTables {
    fn inference_server(&self) -> InferenceServerTableHandle<'_> {
        InferenceServerTableHandle {
            imp: self.imp.get_table::<InferenceServer>("inference_server"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InferenceServerInsertCallbackId(__sdk::CallbackId);
pub struct InferenceServerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InferenceServerTableHandle<'ctx> {
    type Row = InferenceServer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InferenceServer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InferenceServerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceServerInsertCallbackId {
        InferenceServerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InferenceServerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InferenceServerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceServerDeleteCallbackId {
        InferenceServerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InferenceServerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `server_id` unique index on the table `inference_server`,
/// which allows point queries on the field of the same name
/// via the [`InferenceServerServerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_server().server_id().find(...)`.
pub struct InferenceServerServerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InferenceServer, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InferenceServerTableHandle<'ctx> {
    /// Get a handle on the `server_id` unique index on the table `inference_server`.
    pub fn server_id(&self) -> InferenceServerServerIdUnique<'ctx> {
        InferenceServerServerIdUnique {
            imp: self.imp.get_unique_constraint::<String>("server_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InferenceServerServerIdUnique<'ctx> {
    /// Find the subscribed row whose `server_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<InferenceServer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InferenceServer>("inference_server");
    _table.add_unique_constraint::<String>("server_id", |row| &row.server_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InferenceServer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InferenceServer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InferenceServer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inference_serverQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InferenceServer`.
    fn inference_server(&self) -> __sdk::__query_builder::Table<InferenceServer>;
}

impl inference_serverQueryTableAccess for __sdk::QueryTableAccessor {
    fn inference_server(&self) -> __sdk::__query_builder::Table<InferenceServer> {
        __sdk::__query_builder::Table::new("inference_server")
    }
}
