// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReassignTaskArgs {
    pub task_id: String,
    pub new_agent_id: String,
}

impl From<ReassignTaskArgs> for super::Reducer {
    fn from(args: ReassignTaskArgs) -> Self {
        Self::ReassignTask {
            task_id: args.task_id,
            new_agent_id: args.new_agent_id,
        }
    }
}

impl __sdk::InModule for ReassignTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reassign_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reassign_task {
    /// Request that the remote module invoke the reducer `reassign_task` to run as soon as possible.
    fn reassign_task(&self, task_id: String, new_agent_id: String) -> __sdk::Result<()> {
        self.reassign_task_then(task_id, new_agent_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reassign_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    fn reassign_task_then(
        &self,
        task_id: String,
        new_agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl reassign_task for super::RemoteReducers {
    fn reassign_task_then(
        &self,
        task_id: String,
        new_agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReassignTaskArgs {
                task_id,
                new_agent_id,
            },
            callback,
        )
    }
}
