// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterRemoteAgentArgs {
    pub agent_id: String,
    pub name: String,
    pub host: String,
    pub project_dir: String,
    pub capabilities_json: String,
    pub tunnel_id: String,
}

impl From<RegisterRemoteAgentArgs> for super::Reducer {
    fn from(args: RegisterRemoteAgentArgs) -> Self {
        Self::RegisterRemoteAgent {
            agent_id: args.agent_id,
            name: args.name,
            host: args.host,
            project_dir: args.project_dir,
            capabilities_json: args.capabilities_json,
            tunnel_id: args.tunnel_id,
        }
    }
}

impl __sdk::InModule for RegisterRemoteAgentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_remote_agent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_remote_agent {
    /// Request that the remote module invoke the reducer `register_remote_agent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    fn register_remote_agent(
        &self,
        agent_id: String,
        name: String,
        host: String,
        project_dir: String,
        capabilities_json: String,
        tunnel_id: String,
    ) -> __sdk::Result<()> {
        self.register_remote_agent_then(agent_id, name, host, project_dir, capabilities_json, tunnel_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_remote_agent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_remote_agent_then(
        &self,
        agent_id: String,
        name: String,
        host: String,
        project_dir: String,
        capabilities_json: String,
        tunnel_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_remote_agent for super::RemoteReducers {
    fn register_remote_agent_then(
        &self,
        agent_id: String,
        name: String,
        host: String,
        project_dir: String,
        capabilities_json: String,
        tunnel_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterRemoteAgentArgs {
                agent_id,
                name,
                host,
                project_dir,
                capabilities_json,
                tunnel_id,
            },
            callback,
        )
    }
}
