// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::remote_agent_type::RemoteAgent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `remote_agent`.
///
/// Obtain a handle from the [`RemoteAgentTableAccess::remote_agent`] method on [`super::RemoteTables`],
/// like `ctx.db.remote_agent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.remote_agent().on_insert(...)`.
pub struct RemoteAgentTableHandle<'ctx> {
    imp: __sdk::TableHandle<RemoteAgent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `remote_agent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RemoteAgentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RemoteAgentTableHandle`], which mediates access to the table `remote_agent`.
    fn remote_agent(&self) -> RemoteAgentTableHandle<'_>;
}

impl RemoteAgentTableAccess for super::RemoteTables {
    fn remote_agent(&self) -> RemoteAgentTableHandle<'_> {
        RemoteAgentTableHandle {
            imp: self.imp.get_table::<RemoteAgent>("remote_agent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RemoteAgentInsertCallbackId(__sdk::CallbackId);
pub struct RemoteAgentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RemoteAgentTableHandle<'ctx> {
    type Row = RemoteAgent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RemoteAgent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RemoteAgentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RemoteAgentInsertCallbackId {
        RemoteAgentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RemoteAgentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RemoteAgentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RemoteAgentDeleteCallbackId {
        RemoteAgentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RemoteAgentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `remote_agent`,
/// which allows point queries on the field of the same name
/// via the [`RemoteAgentAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.remote_agent().agent_id().find(...)`.
pub struct RemoteAgentAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RemoteAgent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RemoteAgentTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `remote_agent`.
    pub fn agent_id(&self) -> RemoteAgentAgentIdUnique<'ctx> {
        RemoteAgentAgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RemoteAgentAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RemoteAgent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RemoteAgent>("remote_agent");
    _table.add_unique_constraint::<String>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RemoteAgent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RemoteAgent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RemoteAgent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait remote_agentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RemoteAgent`.
    fn remote_agent(&self) -> __sdk::__query_builder::Table<RemoteAgent>;
}

impl remote_agentQueryTableAccess for __sdk::QueryTableAccessor {
    fn remote_agent(&self) -> __sdk::__query_builder::Table<RemoteAgent> {
        __sdk::__query_builder::Table::new("remote_agent")
    }
}
