// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RemoteAgent {
    pub agent_id: String,
    pub name: String,
    pub host: String,
    pub project_dir: String,
    pub status: String,
    pub capabilities_json: String,
    pub last_heartbeat: u64,
    pub connected_at: u64,
    pub tunnel_id: String,
}

impl __sdk::InModule for RemoteAgent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RemoteAgent`.
///
/// Provides typed access to columns for query building.
pub struct RemoteAgentCols {
    pub agent_id: __sdk::__query_builder::Col<RemoteAgent, String>,
    pub name: __sdk::__query_builder::Col<RemoteAgent, String>,
    pub host: __sdk::__query_builder::Col<RemoteAgent, String>,
    pub project_dir: __sdk::__query_builder::Col<RemoteAgent, String>,
    pub status: __sdk::__query_builder::Col<RemoteAgent, String>,
    pub capabilities_json: __sdk::__query_builder::Col<RemoteAgent, String>,
    pub last_heartbeat: __sdk::__query_builder::Col<RemoteAgent, u64>,
    pub connected_at: __sdk::__query_builder::Col<RemoteAgent, u64>,
    pub tunnel_id: __sdk::__query_builder::Col<RemoteAgent, String>,
}

impl __sdk::__query_builder::HasCols for RemoteAgent {
    type Cols = RemoteAgentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RemoteAgentCols {
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            project_dir: __sdk::__query_builder::Col::new(table_name, "project_dir"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            capabilities_json: __sdk::__query_builder::Col::new(table_name, "capabilities_json"),
            last_heartbeat: __sdk::__query_builder::Col::new(table_name, "last_heartbeat"),
            connected_at: __sdk::__query_builder::Col::new(table_name, "connected_at"),
            tunnel_id: __sdk::__query_builder::Col::new(table_name, "tunnel_id"),
        }
    }
}

/// Indexed column accessor struct for the table `RemoteAgent`.
///
/// Provides typed access to indexed columns for query building.
pub struct RemoteAgentIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<RemoteAgent, String>,
}

impl __sdk::__query_builder::HasIxCols for RemoteAgent {
    type IxCols = RemoteAgentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RemoteAgentIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RemoteAgent {}
