// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateHeartbeatArgs {
    pub agent_id: String,
    pub timestamp: u64,
}

impl From<UpdateHeartbeatArgs> for super::Reducer {
    fn from(args: UpdateHeartbeatArgs) -> Self {
        Self::UpdateHeartbeat {
            agent_id: args.agent_id,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for UpdateHeartbeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_heartbeat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_heartbeat {
    /// Request that the remote module invoke the reducer `update_heartbeat` to run as soon as possible.
    fn update_heartbeat(&self, agent_id: String, timestamp: u64) -> __sdk::Result<()> {
        self.update_heartbeat_then(agent_id, timestamp, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_heartbeat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    fn update_heartbeat_then(
        &self,
        agent_id: String,
        timestamp: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_heartbeat for super::RemoteReducers {
    fn update_heartbeat_then(
        &self,
        agent_id: String,
        timestamp: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateHeartbeatArgs {
                agent_id,
                timestamp,
            },
            callback,
        )
    }
}
