// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  requestId: __t.u64(),
  contentJson: __t.string(),
  modelUsed: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cacheReadTokens: __t.u64(),
  cacheWriteTokens: __t.u64(),
  latencyMs: __t.u64(),
  costUsd: __t.string(),
  openrouterCostUsd: __t.string(),
  createdAt: __t.string(),
};
