// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  responseId: __t.u64().primaryKey().name("response_id"),
  requestId: __t.u64().name("request_id"),
  agentId: __t.string().name("agent_id"),
  status: __t.string(),
  contentJson: __t.string().name("content_json"),
  modelUsed: __t.string().name("model_used"),
  inputTokens: __t.u64().name("input_tokens"),
  outputTokens: __t.u64().name("output_tokens"),
  cacheReadTokens: __t.u64().name("cache_read_tokens"),
  cacheWriteTokens: __t.u64().name("cache_write_tokens"),
  latencyMs: __t.u64().name("latency_ms"),
  costUsd: __t.string().name("cost_usd"),
  openrouterCostUsd: __t.string().name("openrouter_cost_usd"),
  createdAt: __t.string().name("created_at"),
});
