// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  providerId: __t.string(),
  providerType: __t.string(),
  baseUrl: __t.string(),
  apiKeyRef: __t.string(),
  modelsJson: __t.string(),
  rateLimitRpm: __t.u32(),
  rateLimitTpm: __t.u64(),
  quantizationLevel: __t.string(),
  contextWindow: __t.u32(),
  qualityScore: __t.f32(),
};
