// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentBudget = __t.object("AgentBudget", {
  agentId: __t.string(),
  totalBudgetTokens: __t.u64(),
  usedTokens: __t.u64(),
  totalBudgetUsd: __t.string(),
  usedUsd: __t.string(),
  maxSingleRequestTokens: __t.u64(),
  updatedAt: __t.string(),
});
export type AgentBudget = __Infer<typeof AgentBudget>;

export const InferenceProvider = __t.object("InferenceProvider", {
  providerId: __t.string(),
  providerType: __t.string(),
  baseUrl: __t.string(),
  apiKeyRef: __t.string(),
  modelsJson: __t.string(),
  rateLimitRpm: __t.u32(),
  rateLimitTpm: __t.u64(),
  currentRpm: __t.u32(),
  currentTpm: __t.u64(),
  healthy: __t.u8(),
  lastHealthCheck: __t.string(),
  avgLatencyMs: __t.u64(),
  quantizationLevel: __t.string(),
  contextWindow: __t.u32(),
  qualityScore: __t.f32(),
});
export type InferenceProvider = __Infer<typeof InferenceProvider>;

export const InferenceRequest = __t.object("InferenceRequest", {
  requestId: __t.u64(),
  agentId: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  messagesJson: __t.string(),
  toolsJson: __t.string(),
  maxTokens: __t.u32(),
  temperature: __t.string(),
  thinkingBudget: __t.u32(),
  cacheControl: __t.u8(),
  priority: __t.u8(),
  status: __t.string(),
  createdAt: __t.string(),
});
export type InferenceRequest = __Infer<typeof InferenceRequest>;

export const InferenceResponse = __t.object("InferenceResponse", {
  responseId: __t.u64(),
  requestId: __t.u64(),
  agentId: __t.string(),
  status: __t.string(),
  contentJson: __t.string(),
  modelUsed: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cacheReadTokens: __t.u64(),
  cacheWriteTokens: __t.u64(),
  latencyMs: __t.u64(),
  costUsd: __t.string(),
  openrouterCostUsd: __t.string(),
  createdAt: __t.string(),
});
export type InferenceResponse = __Infer<typeof InferenceResponse>;

export const InferenceStreamChunk = __t.object("InferenceStreamChunk", {
  chunkId: __t.u64(),
  requestId: __t.u64(),
  agentId: __t.string(),
  chunkType: __t.string(),
  content: __t.string(),
  sequence: __t.u32(),
  createdAt: __t.string(),
});
export type InferenceStreamChunk = __Infer<typeof InferenceStreamChunk>;

