// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  providerId: __t.string().primaryKey().name("provider_id"),
  providerType: __t.string().name("provider_type"),
  baseUrl: __t.string().name("base_url"),
  apiKeyRef: __t.string().name("api_key_ref"),
  modelsJson: __t.string().name("models_json"),
  rateLimitRpm: __t.u32().name("rate_limit_rpm"),
  rateLimitTpm: __t.u64().name("rate_limit_tpm"),
  currentRpm: __t.u32().name("current_rpm"),
  currentTpm: __t.u64().name("current_tpm"),
  healthy: __t.u8(),
  lastHealthCheck: __t.string().name("last_health_check"),
  avgLatencyMs: __t.u64().name("avg_latency_ms"),
});
