// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  agentId: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  messagesJson: __t.string(),
  toolsJson: __t.string(),
  maxTokens: __t.u32(),
  temperature: __t.string(),
  thinkingBudget: __t.u32(),
  cacheControl: __t.u8(),
  priority: __t.u8(),
  createdAt: __t.string(),
};
