#!/usr/bin/env bash
# Start script for Implement domain models (Driver, Race, Constructor) in domain layer
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
