//! README.md generation and ADR sync (ADR-055).

use anyhow::{Context, Result};
use clap::Subcommand;
use colored::Colorize;
use std::path::Path;

use super::interview::{ProjectInterview, ProjectLanguage};

/// Generate a README.md from a project interview.
pub fn generate_readme(interview: &ProjectInterview) -> String {
    let today = chrono::Utc::now().format("%Y-%m-%d").to_string();

    let lang_str = interview.language.to_string();
    let type_str = interview.project_type.to_string();

    let constraints_section = if interview.constraints.is_empty() {
        String::new()
    } else {
        let items: Vec<String> = interview
            .constraints
            .iter()
            .map(|c| format!("- {}", c))
            .collect();
        format!("\n### Constraints\n\n{}\n", items.join("\n"))
    };

    let deps_section = if interview.dependencies.is_empty() {
        String::new()
    } else {
        let rows: Vec<String> = interview
            .dependencies
            .iter()
            .map(|d| format!("| {} | {} |", d.name, d.purpose))
            .collect();
        format!(
            "\n### External Dependencies\n\n| Dependency | Purpose |\n|-----------|----------|\n{}\n",
            rows.join("\n")
        )
    };

    let getting_started = match &interview.language {
        ProjectLanguage::Rust => "```bash\nhex nexus start        # Start the development nexus\nhex analyze .          # Check architecture health\ncargo build            # Build the project\ncargo test             # Run tests\n```",
        ProjectLanguage::Go => "```bash\nhex nexus start        # Start the development nexus\nhex analyze .          # Check architecture health\ngo build ./...         # Build the project\ngo test ./...          # Run tests\n```",
        ProjectLanguage::TypeScript => "```bash\nhex nexus start        # Start the development nexus\nhex analyze .          # Check architecture health\nbun install            # Install dependencies\nbun run build          # Build the project\nbun test               # Run tests\n```",
        ProjectLanguage::Python => "```bash\nhex nexus start        # Start the development nexus\nhex analyze .          # Check architecture health\npip install -e .       # Install in development mode\npytest                 # Run tests\n```",
        ProjectLanguage::Multi(_) => "```bash\nhex nexus start        # Start the development nexus\nhex analyze .          # Check architecture health\n```",
    };

    format!(
        r#"# {name}

{description}

<!-- hex:scope -->
## Project Scope

- **Type**: {project_type}
- **Primary Language**: {language}
- **Created**: {today}
- **Status**: Inception

## Architecture

Hexagonal architecture (Ports & Adapters) enforced by [hex](https://github.com/hex-intf/hex).
{constraints}{deps}
<!-- /hex:scope -->

## Architecture Decisions

<!-- hex:adr-summary — auto-updated by hex -->
No ADRs recorded yet. Use `hex adr create` to record decisions.
<!-- /hex:adr-summary -->

## Getting Started

{getting_started}

## Development

```bash
hex analyze .          # Architecture health check
hex validate           # Semantic validation
hex adr list           # List architecture decisions
hex readme sync-adrs   # Update ADR summary in this README
```

---
*This README is the project specification. Generated by `hex init` and kept current as architecture decisions are made. Last updated: {today}.*
"#,
        name = interview.name,
        description = interview.description,
        project_type = type_str,
        language = lang_str,
        today = today,
        constraints = constraints_section,
        deps = deps_section,
        getting_started = getting_started,
    )
}

/// Parsed ADR summary for the README table.
#[derive(Debug)]
pub struct AdrSummary {
    pub number: String,
    pub title: String,
    pub status: String,
}

/// Parse all ADR files in a directory and extract summaries.
pub fn parse_adr_summaries(adr_dir: &Path) -> Result<Vec<AdrSummary>> {
    let mut summaries = Vec::new();

    if !adr_dir.exists() {
        return Ok(summaries);
    }

    let mut entries: Vec<_> = std::fs::read_dir(adr_dir)?
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.file_name().to_string_lossy().starts_with("ADR-")
                && e.file_name().to_string_lossy().ends_with(".md")
        })
        .collect();

    entries.sort_by_key(|e| e.file_name().to_string_lossy().to_string());

    for entry in entries {
        let content = std::fs::read_to_string(entry.path())?;
        let filename = entry.file_name().to_string_lossy().to_string();

        // Extract number from filename: ADR-055-foo.md -> 055
        let number = filename
            .strip_prefix("ADR-")
            .and_then(|s| s.split('-').next())
            .unwrap_or("???")
            .to_string();

        // Extract title from first H1 line
        let title = content
            .lines()
            .find(|l| l.starts_with("# "))
            .map(|l| {
                // Strip "# ADR-NNN: " prefix if present
                let t = l.trim_start_matches("# ");
                if let Some(rest) = t.split_once(": ") {
                    rest.1.to_string()
                } else {
                    t.to_string()
                }
            })
            .unwrap_or_else(|| filename.clone());

        // Extract status from **Status:** line
        let status = content
            .lines()
            .find(|l| l.contains("**Status:**"))
            .map(|l| l.replace("**Status:**", "").trim().to_string())
            .unwrap_or_else(|| "Unknown".to_string());

        summaries.push(AdrSummary {
            number,
            title,
            status,
        });
    }

    Ok(summaries)
}

/// Regenerate the ADR summary table between sentinel comments in README.md.
pub fn sync_adr_section(readme_path: &Path, adr_dir: &Path) -> Result<bool> {
    if !readme_path.exists() {
        anyhow::bail!("README.md not found at {}", readme_path.display());
    }

    let content =
        std::fs::read_to_string(readme_path).context("Failed to read README.md")?;

    let start_sentinel = "<!-- hex:adr-summary";
    let end_sentinel = "<!-- /hex:adr-summary -->";

    let start_pos = content.find(start_sentinel);
    let end_pos = content.find(end_sentinel);

    let summaries = parse_adr_summaries(adr_dir)?;

    let table = if summaries.is_empty() {
        "No ADRs recorded yet. Use `hex adr create` to record decisions.".to_string()
    } else {
        let mut rows = vec![
            "| ADR | Title | Status |".to_string(),
            "|-----|-------|--------|".to_string(),
        ];
        for s in &summaries {
            rows.push(format!("| {} | {} | {} |", s.number, s.title, s.status));
        }
        rows.join("\n")
    };

    let new_section = format!(
        "<!-- hex:adr-summary — auto-updated by hex -->\n{}\n{}",
        table, end_sentinel
    );

    let new_content = match (start_pos, end_pos) {
        (Some(start), Some(end)) => {
            let before = &content[..start];
            let after = &content[end + end_sentinel.len()..];
            format!("{}{}{}", before, new_section, after)
        }
        _ => {
            // No sentinels found — append section before the last ---
            if let Some(hr_pos) = content.rfind("\n---\n") {
                let before = &content[..hr_pos];
                let after = &content[hr_pos..];
                format!(
                    "{}\n\n## Architecture Decisions\n\n{}\n{}",
                    before, new_section, after
                )
            } else {
                format!(
                    "{}\n\n## Architecture Decisions\n\n{}\n",
                    content.trim_end(),
                    new_section
                )
            }
        }
    };

    if new_content != content {
        std::fs::write(readme_path, &new_content).context("Failed to write README.md")?;
        Ok(true)
    } else {
        Ok(false)
    }
}

// ── CLI subcommand ──────────────────────────────────────────────────────

#[derive(Subcommand)]
pub enum ReadmeAction {
    /// Regenerate ADR summary table in README.md
    SyncAdrs,
    /// Re-run the project interview and update README scope
    Interview,
}

pub async fn run(action: ReadmeAction) -> Result<()> {
    let cwd = std::env::current_dir().context("Failed to get current directory")?;
    let readme_path = cwd.join("README.md");
    let adr_dir = cwd.join("docs/adrs");

    match action {
        ReadmeAction::SyncAdrs => {
            let updated = sync_adr_section(&readme_path, &adr_dir)?;
            if updated {
                let summaries = parse_adr_summaries(&adr_dir)?;
                let accepted = summaries
                    .iter()
                    .filter(|s| s.status.contains("Accepted"))
                    .count();
                let proposed = summaries
                    .iter()
                    .filter(|s| s.status.contains("Proposed"))
                    .count();
                let other = summaries.len() - accepted - proposed;
                println!(
                    "{} Updated ADR summary: {} accepted, {} proposed, {} other",
                    "\u{2b21}".cyan(),
                    accepted.to_string().green(),
                    proposed.to_string().yellow(),
                    other
                );
            } else {
                println!("{} ADR summary already up to date", "\u{2b21}".cyan());
            }
            Ok(())
        }
        ReadmeAction::Interview => {
            let project_name = cwd
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_else(|| "project".to_string());
            let iv = super::interview::run_interview(&project_name)?;
            let content = generate_readme(&iv);

            // If README exists, only update the scope section
            if readme_path.exists() {
                let existing = std::fs::read_to_string(&readme_path)?;
                let scope_start = "<!-- hex:scope -->";
                let scope_end = "<!-- /hex:scope -->";
                if let (Some(s), Some(e)) =
                    (existing.find(scope_start), existing.find(scope_end))
                {
                    // Extract the new scope section from generated content
                    if let (Some(ns), Some(ne)) =
                        (content.find(scope_start), content.find(scope_end))
                    {
                        let new_scope = &content[ns..ne + scope_end.len()];
                        let before = &existing[..s];
                        let after = &existing[e + scope_end.len()..];
                        let updated = format!("{}{}{}", before, new_scope, after);
                        std::fs::write(&readme_path, updated)?;
                        println!(
                            "{} README.md scope section updated",
                            "\u{2b21}".cyan()
                        );
                        return Ok(());
                    }
                }
            }

            // No existing README or no sentinels — write full README
            std::fs::write(&readme_path, content)?;
            println!("{} README.md generated", "\u{2b21}".cyan());
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn parse_adr_summaries_extracts_title_and_status() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("ADR-001-test.md"), "# ADR-001: Test Decision\n\n**Status:** Accepted\n").unwrap();
        fs::write(dir.path().join("ADR-002-another.md"), "# ADR-002: Another One\n\n**Status:** Proposed\n").unwrap();

        let summaries = parse_adr_summaries(dir.path()).unwrap();
        assert_eq!(summaries.len(), 2);
        assert_eq!(summaries[0].number, "001");
        assert_eq!(summaries[0].title, "Test Decision");
        assert!(summaries[0].status.contains("Accepted"));
        assert_eq!(summaries[1].number, "002");
        assert!(summaries[1].status.contains("Proposed"));
    }

    #[test]
    fn parse_adr_summaries_handles_missing_status() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("ADR-010-no-status.md"), "# ADR-010: No Status Line\n\nJust content.\n").unwrap();

        let summaries = parse_adr_summaries(dir.path()).unwrap();
        assert_eq!(summaries.len(), 1);
        assert_eq!(summaries[0].status, "Unknown");
    }

    #[test]
    fn parse_adr_summaries_empty_dir() {
        let dir = tempfile::tempdir().unwrap();
        let summaries = parse_adr_summaries(dir.path()).unwrap();
        assert!(summaries.is_empty());
    }

    #[test]
    fn sync_adr_section_replaces_between_sentinels() {
        let dir = tempfile::tempdir().unwrap();
        let readme = dir.path().join("README.md");
        let adr_dir = dir.path().join("adrs");
        fs::create_dir(&adr_dir).unwrap();

        fs::write(&readme, "# Project\n\n<!-- hex:adr-summary — auto-updated by hex -->\nOLD CONTENT\n<!-- /hex:adr-summary -->\n\nFooter\n").unwrap();
        fs::write(adr_dir.join("ADR-001-foo.md"), "# ADR-001: Foo\n\n**Status:** Accepted\n").unwrap();

        let updated = sync_adr_section(&readme, &adr_dir).unwrap();
        assert!(updated);

        let content = fs::read_to_string(&readme).unwrap();
        assert!(content.contains("| 001 | Foo | Accepted |"));
        assert!(!content.contains("OLD CONTENT"));
        assert!(content.contains("Footer"));
    }

    #[test]
    fn sync_adr_section_appends_when_no_sentinels() {
        let dir = tempfile::tempdir().unwrap();
        let readme = dir.path().join("README.md");
        let adr_dir = dir.path().join("adrs");
        fs::create_dir(&adr_dir).unwrap();

        fs::write(&readme, "# Project\n\nSome content.\n").unwrap();
        fs::write(adr_dir.join("ADR-001-bar.md"), "# ADR-001: Bar\n\n**Status:** Proposed\n").unwrap();

        let updated = sync_adr_section(&readme, &adr_dir).unwrap();
        assert!(updated);

        let content = fs::read_to_string(&readme).unwrap();
        assert!(content.contains("hex:adr-summary"));
        assert!(content.contains("| 001 | Bar | Proposed |"));
    }

    #[test]
    fn generate_readme_includes_language_specific_commands() {
        let iv = super::super::interview::ProjectInterview {
            name: "test-proj".to_string(),
            description: "A test project".to_string(),
            language: super::super::interview::ProjectLanguage::Rust,
            project_type: super::super::interview::ProjectType::Cli,
            constraints: vec!["Must be fast".to_string()],
            dependencies: vec![],
        };
        let readme = generate_readme(&iv);
        assert!(readme.contains("cargo build"));
        assert!(readme.contains("test-proj"));
        assert!(readme.contains("Must be fast"));
        assert!(readme.contains("hex:adr-summary"));
    }
}
