// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Message {
    pub id: String,
    pub conversation_id: String,
    pub role: String,
    pub sender_name: String,
    pub content: String,
    pub timestamp: String,
}

impl __sdk::InModule for Message {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Message`.
///
/// Provides typed access to columns for query building.
pub struct MessageCols {
    pub id: __sdk::__query_builder::Col<Message, String>,
    pub conversation_id: __sdk::__query_builder::Col<Message, String>,
    pub role: __sdk::__query_builder::Col<Message, String>,
    pub sender_name: __sdk::__query_builder::Col<Message, String>,
    pub content: __sdk::__query_builder::Col<Message, String>,
    pub timestamp: __sdk::__query_builder::Col<Message, String>,
}

impl __sdk::__query_builder::HasCols for Message {
    type Cols = MessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            conversation_id: __sdk::__query_builder::Col::new(table_name, "conversation_id"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            sender_name: __sdk::__query_builder::Col::new(table_name, "sender_name"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `Message`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageIxCols {
    pub id: __sdk::__query_builder::IxCol<Message, String>,
}

impl __sdk::__query_builder::HasIxCols for Message {
    type IxCols = MessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Message {}
