#!/usr/bin/env bash
# Start script for Implement integration tests for F1 data flow (end-to-end validation)
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
