// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterHookArgs {
    pub id: String,
    pub event_type: String,
    pub handler_type: String,
    pub handler_config_json: String,
    pub timeout_secs: u32,
    pub blocking: bool,
    pub tool_pattern: String,
    pub timestamp: String,
}

impl From<RegisterHookArgs> for super::Reducer {
    fn from(args: RegisterHookArgs) -> Self {
        Self::RegisterHook {
            id: args.id,
            event_type: args.event_type,
            handler_type: args.handler_type,
            handler_config_json: args.handler_config_json,
            timeout_secs: args.timeout_secs,
            blocking: args.blocking,
            tool_pattern: args.tool_pattern,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for RegisterHookArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_hook`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_hook {
    /// Request that the remote module invoke the reducer `register_hook` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_hook:register_hook_then`] to run a callback after the reducer completes.
    fn register_hook(
        &self,
        id: String,
        event_type: String,
        handler_type: String,
        handler_config_json: String,
        timeout_secs: u32,
        blocking: bool,
        tool_pattern: String,
        timestamp: String,
    ) -> __sdk::Result<()> {
        self.register_hook_then(
            id,
            event_type,
            handler_type,
            handler_config_json,
            timeout_secs,
            blocking,
            tool_pattern,
            timestamp,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_hook` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_hook_then(
        &self,
        id: String,
        event_type: String,
        handler_type: String,
        handler_config_json: String,
        timeout_secs: u32,
        blocking: bool,
        tool_pattern: String,
        timestamp: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_hook for super::RemoteReducers {
    fn register_hook_then(
        &self,
        id: String,
        event_type: String,
        handler_type: String,
        handler_config_json: String,
        timeout_secs: u32,
        blocking: bool,
        tool_pattern: String,
        timestamp: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterHookArgs {
                id,
                event_type,
                handler_type,
                handler_config_json,
                timeout_secs,
                blocking,
                tool_pattern,
                timestamp,
            },
            callback,
        )
    }
}
