// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  adr: __t.string(),
  operation: __t.string(),
  condition: __t.string(),
  severity: __t.string(),
  enabled: __t.u8(),
  projectId: __t.string().name("project_id"),
  message: __t.string(),
  filePatterns: __t.string().name("file_patterns"),
  violationPatterns: __t.string().name("violation_patterns"),
  createdAt: __t.string().name("created_at"),
  updatedAt: __t.string().name("updated_at"),
});
