// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  gateTaskId: __t.string().name("gate_task_id"),
  swarmId: __t.string().name("swarm_id"),
  fixType: __t.string().name("fix_type"),
  targetFile: __t.string().name("target_file"),
  errorContext: __t.string().name("error_context"),
  modelUsed: __t.string().name("model_used"),
  tokens: __t.u64(),
  costUsd: __t.string().name("cost_usd"),
  status: __t.string(),
  result: __t.string(),
  createdAt: __t.string().name("created_at"),
  completedAt: __t.string().name("completed_at"),
});
