// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  host: __t.string(),
  projectId: __t.string().name("project_id"),
  projectDir: __t.string().name("project_dir"),
  model: __t.string(),
  sessionId: __t.string().name("session_id"),
  status: __t.string(),
  swarmId: __t.string().name("swarm_id"),
  role: __t.string(),
  worktreePath: __t.string().name("worktree_path"),
  registeredAt: __t.string().name("registered_at"),
  lastHeartbeat: __t.string().name("last_heartbeat"),
  capabilitiesJson: __t.string().name("capabilities_json"),
});
