// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  serverId: __t.string().primaryKey().name("server_id"),
  name: __t.string(),
  host: __t.string(),
  provider: __t.string(),
  modelsJson: __t.string().name("models_json"),
  status: __t.string(),
  lastHealthCheck: __t.string().name("last_health_check"),
  registeredAt: __t.string().name("registered_at"),
});
