// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  name: __t.string().primaryKey(),
  category: __t.string(),
  description: __t.string(),
  routeMethod: __t.string().name("route_method"),
  routePath: __t.string().name("route_path"),
  inputSchema: __t.string().name("input_schema"),
  version: __t.string(),
  syncedAt: __t.string().name("synced_at"),
});
