// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  projectId: __t.string().primaryKey().name("project_id"),
  name: __t.string(),
  description: __t.string(),
  path: __t.string(),
  registeredAt: __t.string().name("registered_at"),
  astIsStub: __t.bool().name("ast_is_stub"),
});
