// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  swarmId: __t.string().name("swarm_id"),
  tier: __t.u32(),
  gateType: __t.string().name("gate_type"),
  targetDir: __t.string().name("target_dir"),
  language: __t.string(),
  status: __t.string(),
  score: __t.u32(),
  grade: __t.string(),
  violationsCount: __t.u32().name("violations_count"),
  errorOutput: __t.string().name("error_output"),
  iteration: __t.u32(),
  createdAt: __t.string().name("created_at"),
  completedAt: __t.string().name("completed_at"),
});
