// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  skillId: __t.string().primaryKey().name("skill_id"),
  projectId: __t.string().name("project_id"),
  name: __t.string(),
  triggerCmd: __t.string().name("trigger_cmd"),
  description: __t.string(),
  sourcePath: __t.string().name("source_path"),
  syncedAt: __t.string().name("synced_at"),
});
