// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  swarmId: __t.string().name("swarm_id"),
  title: __t.string(),
  status: __t.string(),
  agentId: __t.string().name("agent_id"),
  result: __t.string(),
  dependsOn: __t.string().name("depends_on"),
  version: __t.u64(),
  claimedBy: __t.string().name("claimed_by"),
  createdAt: __t.string().name("created_at"),
  completedAt: __t.string().name("completed_at"),
});
