// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  agentDefId: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  model: __t.string(),
  capabilitiesJson: __t.string(),
  toolsJson: __t.string(),
  sourcePath: __t.string(),
  syncedAt: __t.string(),
};
