// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentDef = __t.object("AgentDef", {
  agentDefId: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  model: __t.string(),
  capabilitiesJson: __t.string(),
  toolsJson: __t.string(),
  sourcePath: __t.string(),
  syncedAt: __t.string(),
});
export type AgentDef = __Infer<typeof AgentDef>;

export const AgentInbox = __t.object("AgentInbox", {
  id: __t.u64(),
  agentId: __t.string(),
  priority: __t.u8(),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.string(),
  acknowledgedAt: __t.string(),
  expiredAt: __t.string(),
});
export type AgentInbox = __Infer<typeof AgentInbox>;

export const HexAgent = __t.object("HexAgent", {
  id: __t.string(),
  name: __t.string(),
  host: __t.string(),
  projectId: __t.string(),
  projectDir: __t.string(),
  model: __t.string(),
  sessionId: __t.string(),
  status: __t.string(),
  swarmId: __t.string(),
  role: __t.string(),
  worktreePath: __t.string(),
  registeredAt: __t.string(),
  lastHeartbeat: __t.string(),
  capabilitiesJson: __t.string(),
});
export type HexAgent = __Infer<typeof HexAgent>;

export const HexFloMemory = __t.object("HexFloMemory", {
  key: __t.string(),
  value: __t.string(),
  scope: __t.string(),
  updatedAt: __t.string(),
});
export type HexFloMemory = __Infer<typeof HexFloMemory>;

export const InferenceServer = __t.object("InferenceServer", {
  serverId: __t.string(),
  name: __t.string(),
  host: __t.string(),
  provider: __t.string(),
  modelsJson: __t.string(),
  status: __t.string(),
  lastHealthCheck: __t.string(),
  registeredAt: __t.string(),
});
export type InferenceServer = __Infer<typeof InferenceServer>;

export const McpTool = __t.object("McpTool", {
  name: __t.string(),
  category: __t.string(),
  description: __t.string(),
  routeMethod: __t.string(),
  routePath: __t.string(),
  inputSchema: __t.string(),
  version: __t.string(),
  syncedAt: __t.string(),
});
export type McpTool = __Infer<typeof McpTool>;

export const Project = __t.object("Project", {
  projectId: __t.string(),
  name: __t.string(),
  description: __t.string(),
  path: __t.string(),
  registeredAt: __t.string(),
});
export type Project = __Infer<typeof Project>;

export const ProjectConfig = __t.object("ProjectConfig", {
  key: __t.string(),
  projectId: __t.string(),
  valueJson: __t.string(),
  sourceFile: __t.string(),
  syncedAt: __t.string(),
});
export type ProjectConfig = __Infer<typeof ProjectConfig>;

export const RemoteAgent = __t.object("RemoteAgent", {
  agentId: __t.string(),
  name: __t.string(),
  host: __t.string(),
  projectDir: __t.string(),
  status: __t.string(),
  capabilitiesJson: __t.string(),
  lastHeartbeat: __t.string(),
  connectedAt: __t.string(),
  tunnelId: __t.string(),
});
export type RemoteAgent = __Infer<typeof RemoteAgent>;

export const SkillEntry = __t.object("SkillEntry", {
  skillId: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  triggerCmd: __t.string(),
  description: __t.string(),
  sourcePath: __t.string(),
  syncedAt: __t.string(),
});
export type SkillEntry = __Infer<typeof SkillEntry>;

export const Swarm = __t.object("Swarm", {
  id: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  topology: __t.string(),
  status: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type Swarm = __Infer<typeof Swarm>;

export const SwarmAgent = __t.object("SwarmAgent", {
  id: __t.string(),
  swarmId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  status: __t.string(),
  worktreePath: __t.string(),
  lastHeartbeat: __t.string(),
});
export type SwarmAgent = __Infer<typeof SwarmAgent>;

export const SwarmTask = __t.object("SwarmTask", {
  id: __t.string(),
  swarmId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  agentId: __t.string(),
  result: __t.string(),
  createdAt: __t.string(),
  completedAt: __t.string(),
});
export type SwarmTask = __Infer<typeof SwarmTask>;

