// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const HexFloMemory = __t.object("HexFloMemory", {
  key: __t.string(),
  value: __t.string(),
  scope: __t.string(),
  updatedAt: __t.string(),
});
export type HexFloMemory = __Infer<typeof HexFloMemory>;

export const Project = __t.object("Project", {
  projectId: __t.string(),
  name: __t.string(),
  path: __t.string(),
  registeredAt: __t.string(),
});
export type Project = __Infer<typeof Project>;

export const Swarm = __t.object("Swarm", {
  id: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  topology: __t.string(),
  status: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type Swarm = __Infer<typeof Swarm>;

export const SwarmAgent = __t.object("SwarmAgent", {
  id: __t.string(),
  swarmId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  status: __t.string(),
  worktreePath: __t.string(),
  lastHeartbeat: __t.string(),
});
export type SwarmAgent = __Infer<typeof SwarmAgent>;

export const SwarmTask = __t.object("SwarmTask", {
  id: __t.string(),
  swarmId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  agentId: __t.string(),
  result: __t.string(),
  createdAt: __t.string(),
  completedAt: __t.string(),
});
export type SwarmTask = __Infer<typeof SwarmTask>;

