// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  projectId: __t.string(),
  language: __t.string(),
  framework: __t.string(),
  outputType: __t.string(),
  architectureStyle: __t.string(),
  constraints: __t.string(),
  activeAdrs: __t.string(),
  workplanObjective: __t.string(),
  fingerprintTokens: __t.u32(),
  generatedAt: __t.string(),
};
