#!/usr/bin/env bash
# Start script for Plan: P1.1: Update ports/api/ergast interface with domain-specific methods
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
