#!/usr/bin/env bash
# Start script for Build Gin-based Todo REST API
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Fetching dependencies..."
go mod tidy

echo "Starting application..."
go run .
