// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DecrementAgentsArgs {
    pub id: String,
}

impl From<DecrementAgentsArgs> for super::Reducer {
    fn from(args: DecrementAgentsArgs) -> Self {
        Self::DecrementAgents { id: args.id }
    }
}

impl __sdk::InModule for DecrementAgentsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decrement_agents`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decrement_agents {
    /// Request that the remote module invoke the reducer `decrement_agents` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`decrement_agents:decrement_agents_then`] to run a callback after the reducer completes.
    fn decrement_agents(&self, id: String) -> __sdk::Result<()> {
        self.decrement_agents_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `decrement_agents` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn decrement_agents_then(
        &self,
        id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl decrement_agents for super::RemoteReducers {
    fn decrement_agents_then(
        &self,
        id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DecrementAgentsArgs { id }, callback)
    }
}
