// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ComputeNode {
    pub id: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub status: String,
    pub max_agents: u32,
    pub active_agents: u32,
    pub last_health_check: String,
}

impl __sdk::InModule for ComputeNode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ComputeNode`.
///
/// Provides typed access to columns for query building.
pub struct ComputeNodeCols {
    pub id: __sdk::__query_builder::Col<ComputeNode, String>,
    pub host: __sdk::__query_builder::Col<ComputeNode, String>,
    pub port: __sdk::__query_builder::Col<ComputeNode, u16>,
    pub username: __sdk::__query_builder::Col<ComputeNode, String>,
    pub status: __sdk::__query_builder::Col<ComputeNode, String>,
    pub max_agents: __sdk::__query_builder::Col<ComputeNode, u32>,
    pub active_agents: __sdk::__query_builder::Col<ComputeNode, u32>,
    pub last_health_check: __sdk::__query_builder::Col<ComputeNode, String>,
}

impl __sdk::__query_builder::HasCols for ComputeNode {
    type Cols = ComputeNodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ComputeNodeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            port: __sdk::__query_builder::Col::new(table_name, "port"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            max_agents: __sdk::__query_builder::Col::new(table_name, "max_agents"),
            active_agents: __sdk::__query_builder::Col::new(table_name, "active_agents"),
            last_health_check: __sdk::__query_builder::Col::new(table_name, "last_health_check"),
        }
    }
}

/// Indexed column accessor struct for the table `ComputeNode`.
///
/// Provides typed access to indexed columns for query building.
pub struct ComputeNodeIxCols {
    pub id: __sdk::__query_builder::IxCol<ComputeNode, String>,
}

impl __sdk::__query_builder::HasIxCols for ComputeNode {
    type IxCols = ComputeNodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ComputeNodeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ComputeNode {}
