// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DecrementAgentsArgs {
    pub id: String,
}

impl From<DecrementAgentsArgs> for super::Reducer {
    fn from(args: DecrementAgentsArgs) -> Self {
        Self::DecrementAgents { id: args.id }
    }
}

impl __sdk::InModule for DecrementAgentsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decrement_agents`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decrement_agents {
    /// Request that the remote module invoke the reducer `decrement_agents` to run as soon as possible.
    fn decrement_agents(&self, id: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `decrement_agents`.
    fn on_decrement_agents(&self, callback: impl FnMut(&super::ReducerEventContext, &DecrementAgentsArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_decrement_agents(&self, callback: __sdk::CallbackId);
}

impl decrement_agents for super::RemoteReducers {
    fn decrement_agents(&self, id: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("decrement_agents", DecrementAgentsArgs { id })
    }

    fn on_decrement_agents(&self, mut callback: impl FnMut(&super::ReducerEventContext, &DecrementAgentsArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("decrement_agents", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::DecrementAgents { id } = &ctx.event.reducer else { unreachable!() };
            let args = DecrementAgentsArgs { id: id.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_decrement_agents(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("decrement_agents", callback);
    }
}
