// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterNodeArgs {
    pub id: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub max_agents: u32,
}

impl From<RegisterNodeArgs> for super::Reducer {
    fn from(args: RegisterNodeArgs) -> Self {
        Self::RegisterNode {
            id: args.id,
            host: args.host,
            port: args.port,
            username: args.username,
            max_agents: args.max_agents,
        }
    }
}

impl __sdk::InModule for RegisterNodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_node {
    /// Request that the remote module invoke the reducer `register_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_node:register_node_then`] to run a callback after the reducer completes.
    fn register_node(
        &self,
        id: String,
        host: String,
        port: u16,
        username: String,
        max_agents: u32,
    ) -> __sdk::Result<()> {
        self.register_node_then(id, host, port, username, max_agents, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_node` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_node_then(
        &self,
        id: String,
        host: String,
        port: u16,
        username: String,
        max_agents: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_node for super::RemoteReducers {
    fn register_node_then(
        &self,
        id: String,
        host: String,
        port: u16,
        username: String,
        max_agents: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterNodeArgs {
                id,
                host,
                port,
                username,
                max_agents,
            },
            callback,
        )
    }
}
