// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterNodeArgs {
    pub id: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub max_agents: u32,
}

impl From<RegisterNodeArgs> for super::Reducer {
    fn from(args: RegisterNodeArgs) -> Self {
        Self::RegisterNode {
            id: args.id,
            host: args.host,
            port: args.port,
            username: args.username,
            max_agents: args.max_agents,
        }
    }
}

impl __sdk::InModule for RegisterNodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_node {
    /// Request that the remote module invoke the reducer `register_node` to run as soon as possible.
    fn register_node(&self, id: String, host: String, port: u16, username: String, max_agents: u32,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_node`.
    fn on_register_node(&self, callback: impl FnMut(&super::ReducerEventContext, &RegisterNodeArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_register_node(&self, callback: __sdk::CallbackId);
}

impl register_node for super::RemoteReducers {
    fn register_node(&self, id: String, host: String, port: u16, username: String, max_agents: u32,) -> __sdk::Result<()> {
        self.imp.call_reducer("register_node", RegisterNodeArgs { id, host, port, username, max_agents })
    }

    fn on_register_node(&self, mut callback: impl FnMut(&super::ReducerEventContext, &RegisterNodeArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("register_node", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::RegisterNode { id, host, port, username, max_agents } = &ctx.event.reducer else { unreachable!() };
            let args = RegisterNodeArgs { id: id.clone(), host: host.clone(), port: port.clone(), username: username.clone(), max_agents: max_agents.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_register_node(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("register_node", callback);
    }
}
