// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateHealthArgs {
    pub id: String,
    pub status: String,
}

impl From<UpdateHealthArgs> for super::Reducer {
    fn from(args: UpdateHealthArgs) -> Self {
        Self::UpdateHealth {
            id: args.id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for UpdateHealthArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_health`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_health {
    /// Request that the remote module invoke the reducer `update_health` to run as soon as possible.
    fn update_health(&self, id: String, status: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_health`.
    fn on_update_health(&self, callback: impl FnMut(&super::ReducerEventContext, &UpdateHealthArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_update_health(&self, callback: __sdk::CallbackId);
}

impl update_health for super::RemoteReducers {
    fn update_health(&self, id: String, status: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("update_health", UpdateHealthArgs { id, status })
    }

    fn on_update_health(&self, mut callback: impl FnMut(&super::ReducerEventContext, &UpdateHealthArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("update_health", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::UpdateHealth { id, status } = &ctx.event.reducer else { unreachable!() };
            let args = UpdateHealthArgs { id: id.clone(), status: status.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_update_health(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("update_health", callback);
    }
}
