#!/usr/bin/env bash
# Start script for URL Shortener REST API Implementation
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
