// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DecrementAgentsReducer from "../decrement_agents_reducer";
import IncrementAgentsReducer from "../increment_agents_reducer";
import RegisterNodeReducer from "../register_node_reducer";
import RemoveNodeReducer from "../remove_node_reducer";
import UpdateHealthReducer from "../update_health_reducer";

export type DecrementAgentsParams = __Infer<typeof DecrementAgentsReducer>;
export type IncrementAgentsParams = __Infer<typeof IncrementAgentsReducer>;
export type RegisterNodeParams = __Infer<typeof RegisterNodeReducer>;
export type RemoveNodeParams = __Infer<typeof RemoveNodeReducer>;
export type UpdateHealthParams = __Infer<typeof UpdateHealthReducer>;

