// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterSkillArgs {
    pub id: String,
    pub name: String,
    pub description: String,
    pub triggers_json: String,
    pub body: String,
    pub source: String,
    pub timestamp: String,
}

impl From<RegisterSkillArgs> for super::Reducer {
    fn from(args: RegisterSkillArgs) -> Self {
        Self::RegisterSkill {
            id: args.id,
            name: args.name,
            description: args.description,
            triggers_json: args.triggers_json,
            body: args.body,
            source: args.source,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for RegisterSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_skill {
    /// Request that the remote module invoke the reducer `register_skill` to run as soon as possible.
    fn register_skill(&self, id: String, name: String, description: String, triggers_json: String, body: String, source: String, timestamp: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_skill`.
    fn on_register_skill(&self, callback: impl FnMut(&super::ReducerEventContext, &RegisterSkillArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_register_skill(&self, callback: __sdk::CallbackId);
}

impl register_skill for super::RemoteReducers {
    fn register_skill(&self, id: String, name: String, description: String, triggers_json: String, body: String, source: String, timestamp: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("register_skill", RegisterSkillArgs { id, name, description, triggers_json, body, source, timestamp })
    }

    fn on_register_skill(&self, mut callback: impl FnMut(&super::ReducerEventContext, &RegisterSkillArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("register_skill", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::RegisterSkill { id, name, description, triggers_json, body, source, timestamp } = &ctx.event.reducer else { unreachable!() };
            let args = RegisterSkillArgs { id: id.clone(), name: name.clone(), description: description.clone(), triggers_json: triggers_json.clone(), body: body.clone(), source: source.clone(), timestamp: timestamp.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_register_skill(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("register_skill", callback);
    }
}
