// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveSkillArgs {
    pub id: String,
}

impl From<RemoveSkillArgs> for super::Reducer {
    fn from(args: RemoveSkillArgs) -> Self {
        Self::RemoveSkill { id: args.id }
    }
}

impl __sdk::InModule for RemoveSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_skill {
    /// Request that the remote module invoke the reducer `remove_skill` to run as soon as possible.
    fn remove_skill(&self, id: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `remove_skill`.
    fn on_remove_skill(&self, callback: impl FnMut(&super::ReducerEventContext, &RemoveSkillArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_remove_skill(&self, callback: __sdk::CallbackId);
}

impl remove_skill for super::RemoteReducers {
    fn remove_skill(&self, id: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("remove_skill", RemoveSkillArgs { id })
    }

    fn on_remove_skill(&self, mut callback: impl FnMut(&super::ReducerEventContext, &RemoveSkillArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("remove_skill", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::RemoveSkill { id } = &ctx.event.reducer else { unreachable!() };
            let args = RemoveSkillArgs { id: id.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_remove_skill(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("remove_skill", callback);
    }
}
