// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SearchSkillsArgs {
    pub trigger_type: String,
    pub query: String,
}

impl From<SearchSkillsArgs> for super::Reducer {
    fn from(args: SearchSkillsArgs) -> Self {
        Self::SearchSkills {
            trigger_type: args.trigger_type,
            query: args.query,
        }
    }
}

impl __sdk::InModule for SearchSkillsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `search_skills`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait search_skills {
    /// Request that the remote module invoke the reducer `search_skills` to run as soon as possible.
    fn search_skills(&self, trigger_type: String, query: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `search_skills`.
    fn on_search_skills(&self, callback: impl FnMut(&super::ReducerEventContext, &SearchSkillsArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_search_skills(&self, callback: __sdk::CallbackId);
}

impl search_skills for super::RemoteReducers {
    fn search_skills(&self, trigger_type: String, query: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("search_skills", SearchSkillsArgs { trigger_type, query })
    }

    fn on_search_skills(&self, mut callback: impl FnMut(&super::ReducerEventContext, &SearchSkillsArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("search_skills", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::SearchSkills { trigger_type, query } = &ctx.event.reducer else { unreachable!() };
            let args = SearchSkillsArgs { trigger_type: trigger_type.clone(), query: query.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_search_skills(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("search_skills", callback);
    }
}
