// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SearchSkillsArgs {
    pub trigger_type: String,
    pub query: String,
}

impl From<SearchSkillsArgs> for super::Reducer {
    fn from(args: SearchSkillsArgs) -> Self {
        Self::SearchSkills {
            trigger_type: args.trigger_type,
            query: args.query,
        }
    }
}

impl __sdk::InModule for SearchSkillsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `search_skills`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait search_skills {
    /// Request that the remote module invoke the reducer `search_skills` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`search_skills:search_skills_then`] to run a callback after the reducer completes.
    fn search_skills(&self, trigger_type: String, query: String) -> __sdk::Result<()> {
        self.search_skills_then(trigger_type, query, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `search_skills` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn search_skills_then(
        &self,
        trigger_type: String,
        query: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl search_skills for super::RemoteReducers {
    fn search_skills_then(
        &self,
        trigger_type: String,
        query: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SearchSkillsArgs {
                trigger_type,
                query,
            },
            callback,
        )
    }
}
