// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSkillArgs {
    pub id: String,
    pub description: String,
    pub triggers_json: String,
    pub body: String,
    pub timestamp: String,
}

impl From<UpdateSkillArgs> for super::Reducer {
    fn from(args: UpdateSkillArgs) -> Self {
        Self::UpdateSkill {
            id: args.id,
            description: args.description,
            triggers_json: args.triggers_json,
            body: args.body,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for UpdateSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_skill {
    /// Request that the remote module invoke the reducer `update_skill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_skill:update_skill_then`] to run a callback after the reducer completes.
    fn update_skill(
        &self,
        id: String,
        description: String,
        triggers_json: String,
        body: String,
        timestamp: String,
    ) -> __sdk::Result<()> {
        self.update_skill_then(id, description, triggers_json, body, timestamp, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_skill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_skill_then(
        &self,
        id: String,
        description: String,
        triggers_json: String,
        body: String,
        timestamp: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_skill for super::RemoteReducers {
    fn update_skill_then(
        &self,
        id: String,
        description: String,
        triggers_json: String,
        body: String,
        timestamp: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateSkillArgs {
                id,
                description,
                triggers_json,
                body,
                timestamp,
            },
            callback,
        )
    }
}
