// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSkillArgs {
    pub id: String,
    pub description: String,
    pub triggers_json: String,
    pub body: String,
    pub timestamp: String,
}

impl From<UpdateSkillArgs> for super::Reducer {
    fn from(args: UpdateSkillArgs) -> Self {
        Self::UpdateSkill {
            id: args.id,
            description: args.description,
            triggers_json: args.triggers_json,
            body: args.body,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for UpdateSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_skill {
    /// Request that the remote module invoke the reducer `update_skill` to run as soon as possible.
    fn update_skill(&self, id: String, description: String, triggers_json: String, body: String, timestamp: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_skill`.
    fn on_update_skill(&self, callback: impl FnMut(&super::ReducerEventContext, &UpdateSkillArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_update_skill(&self, callback: __sdk::CallbackId);
}

impl update_skill for super::RemoteReducers {
    fn update_skill(&self, id: String, description: String, triggers_json: String, body: String, timestamp: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("update_skill", UpdateSkillArgs { id, description, triggers_json, body, timestamp })
    }

    fn on_update_skill(&self, mut callback: impl FnMut(&super::ReducerEventContext, &UpdateSkillArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("update_skill", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::UpdateSkill { id, description, triggers_json, body, timestamp } = &ctx.event.reducer else { unreachable!() };
            let args = UpdateSkillArgs { id: id.clone(), description: description.clone(), triggers_json: triggers_json.clone(), body: body.clone(), timestamp: timestamp.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_update_skill(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("update_skill", callback);
    }
}
