#!/usr/bin/env bash
# Start script for Implement Todo REST API with Hexagonal Layers
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Building..."
cargo build --release

echo "Starting application..."
./target/release/$(basename $(pwd))
