//! Generated SpacetimeDB client bindings for all hex WASM modules.
//!
//! These bindings are auto-generated by `spacetime generate --lang rust`.
//! Do NOT edit manually — regenerate after publishing module changes.
//!
//! Each sub-module provides a `DbConnection` with `.db` (table access)
//! and `.reducers` (reducer calls) for one SpacetimeDB database.

#[cfg(feature = "spacetimedb")]
pub mod rl_engine;
#[cfg(feature = "spacetimedb")]
pub mod agent_registry;
#[cfg(feature = "spacetimedb")]
pub mod chat_relay;
#[cfg(feature = "spacetimedb")]
pub mod inference_gateway;
#[cfg(feature = "spacetimedb")]
pub mod secret_grant;
