// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_budget_type::AgentBudget;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_budget`.
///
/// Obtain a handle from the [`AgentBudgetTableAccess::agent_budget`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_budget()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_budget().on_insert(...)`.
pub struct AgentBudgetTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentBudget>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_budget`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentBudgetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentBudgetTableHandle`], which mediates access to the table `agent_budget`.
    fn agent_budget(&self) -> AgentBudgetTableHandle<'_>;
}

impl AgentBudgetTableAccess for super::RemoteTables {
    fn agent_budget(&self) -> AgentBudgetTableHandle<'_> {
        AgentBudgetTableHandle {
            imp: self.imp.get_table::<AgentBudget>("agent_budget"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentBudgetInsertCallbackId(__sdk::CallbackId);
pub struct AgentBudgetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentBudgetTableHandle<'ctx> {
    type Row = AgentBudget;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentBudget> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentBudgetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentBudgetInsertCallbackId {
        AgentBudgetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentBudgetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentBudgetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentBudgetDeleteCallbackId {
        AgentBudgetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentBudgetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentBudgetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentBudgetTableHandle<'ctx> {
    type UpdateCallbackId = AgentBudgetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentBudgetUpdateCallbackId {
        AgentBudgetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentBudgetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `agent_budget`,
/// which allows point queries on the field of the same name
/// via the [`AgentBudgetAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_budget().agent_id().find(...)`.
pub struct AgentBudgetAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentBudget, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentBudgetTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `agent_budget`.
    pub fn agent_id(&self) -> AgentBudgetAgentIdUnique<'ctx> {
        AgentBudgetAgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentBudgetAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgentBudget> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentBudget>("agent_budget");
    _table.add_unique_constraint::<String>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentBudget>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentBudget>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentBudget`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_budgetQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentBudget`.
    fn agent_budget(&self) -> __sdk::__query_builder::Table<AgentBudget>;
}

impl agent_budgetQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_budget(&self) -> __sdk::__query_builder::Table<AgentBudget> {
        __sdk::__query_builder::Table::new("agent_budget")
    }
}
