// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendStreamChunkArgs {
    pub request_id: u64,
    pub agent_id: String,
    pub chunk_type: String,
    pub content: String,
    pub sequence: u32,
    pub created_at: String,
}

impl From<AppendStreamChunkArgs> for super::Reducer {
    fn from(args: AppendStreamChunkArgs) -> Self {
        Self::AppendStreamChunk {
            request_id: args.request_id,
            agent_id: args.agent_id,
            chunk_type: args.chunk_type,
            content: args.content,
            sequence: args.sequence,
            created_at: args.created_at,
        }
    }
}

impl __sdk::InModule for AppendStreamChunkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_stream_chunk`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_stream_chunk {
    /// Request that the remote module invoke the reducer `append_stream_chunk` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_stream_chunk:append_stream_chunk_then`] to run a callback after the reducer completes.
    fn append_stream_chunk(
        &self,
        request_id: u64,
        agent_id: String,
        chunk_type: String,
        content: String,
        sequence: u32,
        created_at: String,
    ) -> __sdk::Result<()> {
        self.append_stream_chunk_then(
            request_id,
            agent_id,
            chunk_type,
            content,
            sequence,
            created_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `append_stream_chunk` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_stream_chunk_then(
        &self,
        request_id: u64,
        agent_id: String,
        chunk_type: String,
        content: String,
        sequence: u32,
        created_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_stream_chunk for super::RemoteReducers {
    fn append_stream_chunk_then(
        &self,
        request_id: u64,
        agent_id: String,
        chunk_type: String,
        content: String,
        sequence: u32,
        created_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AppendStreamChunkArgs {
                request_id,
                agent_id,
                chunk_type,
                content,
                sequence,
                created_at,
            },
            callback,
        )
    }
}
