// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CompleteInferenceArgs {
    pub request_id: u64,
    pub content_json: String,
    pub model_used: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read_tokens: u64,
    pub cache_write_tokens: u64,
    pub latency_ms: u64,
    pub cost_usd: String,
    pub openrouter_cost_usd: String,
    pub created_at: String,
}

impl From<CompleteInferenceArgs> for super::Reducer {
    fn from(args: CompleteInferenceArgs) -> Self {
        Self::CompleteInference {
            request_id: args.request_id,
            content_json: args.content_json,
            model_used: args.model_used,
            input_tokens: args.input_tokens,
            output_tokens: args.output_tokens,
            cache_read_tokens: args.cache_read_tokens,
            cache_write_tokens: args.cache_write_tokens,
            latency_ms: args.latency_ms,
            cost_usd: args.cost_usd,
            openrouter_cost_usd: args.openrouter_cost_usd,
            created_at: args.created_at,
        }
    }
}

impl __sdk::InModule for CompleteInferenceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `complete_inference`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait complete_inference {
    /// Request that the remote module invoke the reducer `complete_inference` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`complete_inference:complete_inference_then`] to run a callback after the reducer completes.
    fn complete_inference(
        &self,
        request_id: u64,
        content_json: String,
        model_used: String,
        input_tokens: u64,
        output_tokens: u64,
        cache_read_tokens: u64,
        cache_write_tokens: u64,
        latency_ms: u64,
        cost_usd: String,
        openrouter_cost_usd: String,
        created_at: String,
    ) -> __sdk::Result<()> {
        self.complete_inference_then(
            request_id,
            content_json,
            model_used,
            input_tokens,
            output_tokens,
            cache_read_tokens,
            cache_write_tokens,
            latency_ms,
            cost_usd,
            openrouter_cost_usd,
            created_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `complete_inference` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn complete_inference_then(
        &self,
        request_id: u64,
        content_json: String,
        model_used: String,
        input_tokens: u64,
        output_tokens: u64,
        cache_read_tokens: u64,
        cache_write_tokens: u64,
        latency_ms: u64,
        cost_usd: String,
        openrouter_cost_usd: String,
        created_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl complete_inference for super::RemoteReducers {
    fn complete_inference_then(
        &self,
        request_id: u64,
        content_json: String,
        model_used: String,
        input_tokens: u64,
        output_tokens: u64,
        cache_read_tokens: u64,
        cache_write_tokens: u64,
        latency_ms: u64,
        cost_usd: String,
        openrouter_cost_usd: String,
        created_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CompleteInferenceArgs {
                request_id,
                content_json,
                model_used,
                input_tokens,
                output_tokens,
                cache_read_tokens,
                cache_write_tokens,
                latency_ms,
                cost_usd,
                openrouter_cost_usd,
                created_at,
            },
            callback,
        )
    }
}
