// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inference_request_type::InferenceRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inference_request`.
///
/// Obtain a handle from the [`InferenceRequestTableAccess::inference_request`] method on [`super::RemoteTables`],
/// like `ctx.db.inference_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_request().on_insert(...)`.
pub struct InferenceRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<InferenceRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inference_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InferenceRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InferenceRequestTableHandle`], which mediates access to the table `inference_request`.
    fn inference_request(&self) -> InferenceRequestTableHandle<'_>;
}

impl InferenceRequestTableAccess for super::RemoteTables {
    fn inference_request(&self) -> InferenceRequestTableHandle<'_> {
        InferenceRequestTableHandle {
            imp: self.imp.get_table::<InferenceRequest>("inference_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InferenceRequestInsertCallbackId(__sdk::CallbackId);
pub struct InferenceRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InferenceRequestTableHandle<'ctx> {
    type Row = InferenceRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InferenceRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InferenceRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceRequestInsertCallbackId {
        InferenceRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InferenceRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InferenceRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceRequestDeleteCallbackId {
        InferenceRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InferenceRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InferenceRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InferenceRequestTableHandle<'ctx> {
    type UpdateCallbackId = InferenceRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InferenceRequestUpdateCallbackId {
        InferenceRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InferenceRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `request_id` unique index on the table `inference_request`,
/// which allows point queries on the field of the same name
/// via the [`InferenceRequestRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_request().request_id().find(...)`.
pub struct InferenceRequestRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InferenceRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InferenceRequestTableHandle<'ctx> {
    /// Get a handle on the `request_id` unique index on the table `inference_request`.
    pub fn request_id(&self) -> InferenceRequestRequestIdUnique<'ctx> {
        InferenceRequestRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("request_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InferenceRequestRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `request_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InferenceRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InferenceRequest>("inference_request");
    _table.add_unique_constraint::<u64>("request_id", |row| &row.request_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InferenceRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InferenceRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InferenceRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inference_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InferenceRequest`.
    fn inference_request(&self) -> __sdk::__query_builder::Table<InferenceRequest>;
}

impl inference_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn inference_request(&self) -> __sdk::__query_builder::Table<InferenceRequest> {
        __sdk::__query_builder::Table::new("inference_request")
    }
}
