// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InferenceStreamChunk {
    pub chunk_id: u64,
    pub request_id: u64,
    pub agent_id: String,
    pub chunk_type: String,
    pub content: String,
    pub sequence: u32,
    pub created_at: String,
}

impl __sdk::InModule for InferenceStreamChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InferenceStreamChunk`.
///
/// Provides typed access to columns for query building.
pub struct InferenceStreamChunkCols {
    pub chunk_id: __sdk::__query_builder::Col<InferenceStreamChunk, u64>,
    pub request_id: __sdk::__query_builder::Col<InferenceStreamChunk, u64>,
    pub agent_id: __sdk::__query_builder::Col<InferenceStreamChunk, String>,
    pub chunk_type: __sdk::__query_builder::Col<InferenceStreamChunk, String>,
    pub content: __sdk::__query_builder::Col<InferenceStreamChunk, String>,
    pub sequence: __sdk::__query_builder::Col<InferenceStreamChunk, u32>,
    pub created_at: __sdk::__query_builder::Col<InferenceStreamChunk, String>,
}

impl __sdk::__query_builder::HasCols for InferenceStreamChunk {
    type Cols = InferenceStreamChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InferenceStreamChunkCols {
            chunk_id: __sdk::__query_builder::Col::new(table_name, "chunk_id"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            chunk_type: __sdk::__query_builder::Col::new(table_name, "chunk_type"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InferenceStreamChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct InferenceStreamChunkIxCols {
    pub chunk_id: __sdk::__query_builder::IxCol<InferenceStreamChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for InferenceStreamChunk {
    type IxCols = InferenceStreamChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InferenceStreamChunkIxCols {
            chunk_id: __sdk::__query_builder::IxCol::new(table_name, "chunk_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InferenceStreamChunk {}
