// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inference_response_type::InferenceResponse;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inference_response`.
///
/// Obtain a handle from the [`InferenceResponseTableAccess::inference_response`] method on [`super::RemoteTables`],
/// like `ctx.db.inference_response()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_response().on_insert(...)`.
pub struct InferenceResponseTableHandle<'ctx> {
    imp: __sdk::TableHandle<InferenceResponse>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inference_response`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InferenceResponseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InferenceResponseTableHandle`], which mediates access to the table `inference_response`.
    fn inference_response(&self) -> InferenceResponseTableHandle<'_>;
}

impl InferenceResponseTableAccess for super::RemoteTables {
    fn inference_response(&self) -> InferenceResponseTableHandle<'_> {
        InferenceResponseTableHandle {
            imp: self
                .imp
                .get_table::<InferenceResponse>("inference_response"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InferenceResponseInsertCallbackId(__sdk::CallbackId);
pub struct InferenceResponseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InferenceResponseTableHandle<'ctx> {
    type Row = InferenceResponse;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InferenceResponse> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InferenceResponseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceResponseInsertCallbackId {
        InferenceResponseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InferenceResponseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InferenceResponseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceResponseDeleteCallbackId {
        InferenceResponseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InferenceResponseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InferenceResponseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InferenceResponseTableHandle<'ctx> {
    type UpdateCallbackId = InferenceResponseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InferenceResponseUpdateCallbackId {
        InferenceResponseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InferenceResponseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `response_id` unique index on the table `inference_response`,
/// which allows point queries on the field of the same name
/// via the [`InferenceResponseResponseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_response().response_id().find(...)`.
pub struct InferenceResponseResponseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InferenceResponse, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InferenceResponseTableHandle<'ctx> {
    /// Get a handle on the `response_id` unique index on the table `inference_response`.
    pub fn response_id(&self) -> InferenceResponseResponseIdUnique<'ctx> {
        InferenceResponseResponseIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("response_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InferenceResponseResponseIdUnique<'ctx> {
    /// Find the subscribed row whose `response_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InferenceResponse> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InferenceResponse>("inference_response");
    _table.add_unique_constraint::<u64>("response_id", |row| &row.response_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InferenceResponse>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InferenceResponse>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InferenceResponse`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inference_responseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InferenceResponse`.
    fn inference_response(&self) -> __sdk::__query_builder::Table<InferenceResponse>;
}

impl inference_responseQueryTableAccess for __sdk::QueryTableAccessor {
    fn inference_response(&self) -> __sdk::__query_builder::Table<InferenceResponse> {
        __sdk::__query_builder::Table::new("inference_response")
    }
}
