// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InferenceProvider {
    pub provider_id: String,
    pub provider_type: String,
    pub base_url: String,
    pub api_key_ref: String,
    pub models_json: String,
    pub rate_limit_rpm: u32,
    pub rate_limit_tpm: u64,
    pub current_rpm: u32,
    pub current_tpm: u64,
    pub healthy: u8,
    pub last_health_check: String,
    pub avg_latency_ms: u64,
    pub quantization_level: String,
    pub context_window: u32,
    pub quality_score: f32,
}

impl __sdk::InModule for InferenceProvider {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InferenceProvider`.
///
/// Provides typed access to columns for query building.
pub struct InferenceProviderCols {
    pub provider_id: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub provider_type: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub base_url: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub api_key_ref: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub models_json: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub rate_limit_rpm: __sdk::__query_builder::Col<InferenceProvider, u32>,
    pub rate_limit_tpm: __sdk::__query_builder::Col<InferenceProvider, u64>,
    pub current_rpm: __sdk::__query_builder::Col<InferenceProvider, u32>,
    pub current_tpm: __sdk::__query_builder::Col<InferenceProvider, u64>,
    pub healthy: __sdk::__query_builder::Col<InferenceProvider, u8>,
    pub last_health_check: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub avg_latency_ms: __sdk::__query_builder::Col<InferenceProvider, u64>,
    pub quantization_level: __sdk::__query_builder::Col<InferenceProvider, String>,
    pub context_window: __sdk::__query_builder::Col<InferenceProvider, u32>,
    pub quality_score: __sdk::__query_builder::Col<InferenceProvider, f32>,
}

impl __sdk::__query_builder::HasCols for InferenceProvider {
    type Cols = InferenceProviderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InferenceProviderCols {
            provider_id: __sdk::__query_builder::Col::new(table_name, "provider_id"),
            provider_type: __sdk::__query_builder::Col::new(table_name, "provider_type"),
            base_url: __sdk::__query_builder::Col::new(table_name, "base_url"),
            api_key_ref: __sdk::__query_builder::Col::new(table_name, "api_key_ref"),
            models_json: __sdk::__query_builder::Col::new(table_name, "models_json"),
            rate_limit_rpm: __sdk::__query_builder::Col::new(table_name, "rate_limit_rpm"),
            rate_limit_tpm: __sdk::__query_builder::Col::new(table_name, "rate_limit_tpm"),
            current_rpm: __sdk::__query_builder::Col::new(table_name, "current_rpm"),
            current_tpm: __sdk::__query_builder::Col::new(table_name, "current_tpm"),
            healthy: __sdk::__query_builder::Col::new(table_name, "healthy"),
            last_health_check: __sdk::__query_builder::Col::new(table_name, "last_health_check"),
            avg_latency_ms: __sdk::__query_builder::Col::new(table_name, "avg_latency_ms"),
            quantization_level: __sdk::__query_builder::Col::new(table_name, "quantization_level"),
            context_window: __sdk::__query_builder::Col::new(table_name, "context_window"),
            quality_score: __sdk::__query_builder::Col::new(table_name, "quality_score"),
        }
    }
}

/// Indexed column accessor struct for the table `InferenceProvider`.
///
/// Provides typed access to indexed columns for query building.
pub struct InferenceProviderIxCols {
    pub provider_id: __sdk::__query_builder::IxCol<InferenceProvider, String>,
}

impl __sdk::__query_builder::HasIxCols for InferenceProvider {
    type IxCols = InferenceProviderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InferenceProviderIxCols {
            provider_id: __sdk::__query_builder::IxCol::new(table_name, "provider_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InferenceProvider {}
