// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InferenceRequest {
    pub request_id: u64,
    pub agent_id: String,
    pub provider: String,
    pub model: String,
    pub messages_json: String,
    pub tools_json: String,
    pub max_tokens: u32,
    pub temperature: String,
    pub thinking_budget: u32,
    pub cache_control: u8,
    pub priority: u8,
    pub status: String,
    pub created_at: String,
}

impl __sdk::InModule for InferenceRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InferenceRequest`.
///
/// Provides typed access to columns for query building.
pub struct InferenceRequestCols {
    pub request_id: __sdk::__query_builder::Col<InferenceRequest, u64>,
    pub agent_id: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub provider: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub model: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub messages_json: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub tools_json: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub max_tokens: __sdk::__query_builder::Col<InferenceRequest, u32>,
    pub temperature: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub thinking_budget: __sdk::__query_builder::Col<InferenceRequest, u32>,
    pub cache_control: __sdk::__query_builder::Col<InferenceRequest, u8>,
    pub priority: __sdk::__query_builder::Col<InferenceRequest, u8>,
    pub status: __sdk::__query_builder::Col<InferenceRequest, String>,
    pub created_at: __sdk::__query_builder::Col<InferenceRequest, String>,
}

impl __sdk::__query_builder::HasCols for InferenceRequest {
    type Cols = InferenceRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InferenceRequestCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            model: __sdk::__query_builder::Col::new(table_name, "model"),
            messages_json: __sdk::__query_builder::Col::new(table_name, "messages_json"),
            tools_json: __sdk::__query_builder::Col::new(table_name, "tools_json"),
            max_tokens: __sdk::__query_builder::Col::new(table_name, "max_tokens"),
            temperature: __sdk::__query_builder::Col::new(table_name, "temperature"),
            thinking_budget: __sdk::__query_builder::Col::new(table_name, "thinking_budget"),
            cache_control: __sdk::__query_builder::Col::new(table_name, "cache_control"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InferenceRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct InferenceRequestIxCols {
    pub request_id: __sdk::__query_builder::IxCol<InferenceRequest, u64>,
}

impl __sdk::__query_builder::HasIxCols for InferenceRequest {
    type IxCols = InferenceRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InferenceRequestIxCols {
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InferenceRequest {}
