// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inference_provider_type::InferenceProvider;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inference_provider`.
///
/// Obtain a handle from the [`InferenceProviderTableAccess::inference_provider`] method on [`super::RemoteTables`],
/// like `ctx.db.inference_provider()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_provider().on_insert(...)`.
pub struct InferenceProviderTableHandle<'ctx> {
    imp: __sdk::TableHandle<InferenceProvider>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inference_provider`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InferenceProviderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InferenceProviderTableHandle`], which mediates access to the table `inference_provider`.
    fn inference_provider(&self) -> InferenceProviderTableHandle<'_>;
}

impl InferenceProviderTableAccess for super::RemoteTables {
    fn inference_provider(&self) -> InferenceProviderTableHandle<'_> {
        InferenceProviderTableHandle {
            imp: self
                .imp
                .get_table::<InferenceProvider>("inference_provider"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InferenceProviderInsertCallbackId(__sdk::CallbackId);
pub struct InferenceProviderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InferenceProviderTableHandle<'ctx> {
    type Row = InferenceProvider;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InferenceProvider> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InferenceProviderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceProviderInsertCallbackId {
        InferenceProviderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InferenceProviderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InferenceProviderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InferenceProviderDeleteCallbackId {
        InferenceProviderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InferenceProviderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InferenceProviderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InferenceProviderTableHandle<'ctx> {
    type UpdateCallbackId = InferenceProviderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InferenceProviderUpdateCallbackId {
        InferenceProviderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InferenceProviderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `provider_id` unique index on the table `inference_provider`,
/// which allows point queries on the field of the same name
/// via the [`InferenceProviderProviderIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inference_provider().provider_id().find(...)`.
pub struct InferenceProviderProviderIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InferenceProvider, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InferenceProviderTableHandle<'ctx> {
    /// Get a handle on the `provider_id` unique index on the table `inference_provider`.
    pub fn provider_id(&self) -> InferenceProviderProviderIdUnique<'ctx> {
        InferenceProviderProviderIdUnique {
            imp: self.imp.get_unique_constraint::<String>("provider_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InferenceProviderProviderIdUnique<'ctx> {
    /// Find the subscribed row whose `provider_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<InferenceProvider> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InferenceProvider>("inference_provider");
    _table.add_unique_constraint::<String>("provider_id", |row| &row.provider_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InferenceProvider>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InferenceProvider>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InferenceProvider`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inference_providerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InferenceProvider`.
    fn inference_provider(&self) -> __sdk::__query_builder::Table<InferenceProvider>;
}

impl inference_providerQueryTableAccess for __sdk::QueryTableAccessor {
    fn inference_provider(&self) -> __sdk::__query_builder::Table<InferenceProvider> {
        __sdk::__query_builder::Table::new("inference_provider")
    }
}
