// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InferenceResponse {
    pub response_id: u64,
    pub request_id: u64,
    pub agent_id: String,
    pub status: String,
    pub content_json: String,
    pub model_used: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read_tokens: u64,
    pub cache_write_tokens: u64,
    pub latency_ms: u64,
    pub cost_usd: String,
    pub openrouter_cost_usd: String,
    pub created_at: String,
}

impl __sdk::InModule for InferenceResponse {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InferenceResponse`.
///
/// Provides typed access to columns for query building.
pub struct InferenceResponseCols {
    pub response_id: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub request_id: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub agent_id: __sdk::__query_builder::Col<InferenceResponse, String>,
    pub status: __sdk::__query_builder::Col<InferenceResponse, String>,
    pub content_json: __sdk::__query_builder::Col<InferenceResponse, String>,
    pub model_used: __sdk::__query_builder::Col<InferenceResponse, String>,
    pub input_tokens: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub output_tokens: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub cache_read_tokens: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub cache_write_tokens: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub latency_ms: __sdk::__query_builder::Col<InferenceResponse, u64>,
    pub cost_usd: __sdk::__query_builder::Col<InferenceResponse, String>,
    pub openrouter_cost_usd: __sdk::__query_builder::Col<InferenceResponse, String>,
    pub created_at: __sdk::__query_builder::Col<InferenceResponse, String>,
}

impl __sdk::__query_builder::HasCols for InferenceResponse {
    type Cols = InferenceResponseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InferenceResponseCols {
            response_id: __sdk::__query_builder::Col::new(table_name, "response_id"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            content_json: __sdk::__query_builder::Col::new(table_name, "content_json"),
            model_used: __sdk::__query_builder::Col::new(table_name, "model_used"),
            input_tokens: __sdk::__query_builder::Col::new(table_name, "input_tokens"),
            output_tokens: __sdk::__query_builder::Col::new(table_name, "output_tokens"),
            cache_read_tokens: __sdk::__query_builder::Col::new(table_name, "cache_read_tokens"),
            cache_write_tokens: __sdk::__query_builder::Col::new(table_name, "cache_write_tokens"),
            latency_ms: __sdk::__query_builder::Col::new(table_name, "latency_ms"),
            cost_usd: __sdk::__query_builder::Col::new(table_name, "cost_usd"),
            openrouter_cost_usd: __sdk::__query_builder::Col::new(
                table_name,
                "openrouter_cost_usd",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InferenceResponse`.
///
/// Provides typed access to indexed columns for query building.
pub struct InferenceResponseIxCols {
    pub response_id: __sdk::__query_builder::IxCol<InferenceResponse, u64>,
}

impl __sdk::__query_builder::HasIxCols for InferenceResponse {
    type IxCols = InferenceResponseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InferenceResponseIxCols {
            response_id: __sdk::__query_builder::IxCol::new(table_name, "response_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InferenceResponse {}
