// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit d60138999206c06c776829072f46b5d1c1101f7e).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod agent_budget_table;
pub mod agent_budget_type;
pub mod append_stream_chunk_reducer;
pub mod complete_inference_reducer;
pub mod fail_inference_reducer;
pub mod inference_provider_table;
pub mod inference_provider_type;
pub mod inference_request_table;
pub mod inference_request_type;
pub mod inference_response_table;
pub mod inference_response_type;
pub mod inference_stream_chunk_table;
pub mod inference_stream_chunk_type;
pub mod register_provider_reducer;
pub mod remove_provider_reducer;
pub mod request_inference_reducer;
pub mod reset_rate_counters_reducer;
pub mod set_agent_budget_reducer;
pub mod set_api_key_reducer;

pub use agent_budget_table::*;
pub use agent_budget_type::AgentBudget;
pub use append_stream_chunk_reducer::append_stream_chunk;
pub use complete_inference_reducer::complete_inference;
pub use fail_inference_reducer::fail_inference;
pub use inference_provider_table::*;
pub use inference_provider_type::InferenceProvider;
pub use inference_request_table::*;
pub use inference_request_type::InferenceRequest;
pub use inference_response_table::*;
pub use inference_response_type::InferenceResponse;
pub use inference_stream_chunk_table::*;
pub use inference_stream_chunk_type::InferenceStreamChunk;
pub use register_provider_reducer::register_provider;
pub use remove_provider_reducer::remove_provider;
pub use request_inference_reducer::request_inference;
pub use reset_rate_counters_reducer::reset_rate_counters;
pub use set_agent_budget_reducer::set_agent_budget;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AppendStreamChunk {
        request_id: u64,
        agent_id: String,
        chunk_type: String,
        content: String,
        sequence: u32,
        created_at: String,
    },
    CompleteInference {
        request_id: u64,
        content_json: String,
        model_used: String,
        input_tokens: u64,
        output_tokens: u64,
        cache_read_tokens: u64,
        cache_write_tokens: u64,
        latency_ms: u64,
        cost_usd: String,
        openrouter_cost_usd: String,
        created_at: String,
    },
    FailInference {
        request_id: u64,
        error_message: String,
        created_at: String,
    },
    RegisterProvider {
        provider_id: String,
        provider_type: String,
        base_url: String,
        api_key_ref: String,
        models_json: String,
        rate_limit_rpm: u32,
        rate_limit_tpm: u64,
        quantization_level: String,
        context_window: u32,
        quality_score: f32,
    },
    RemoveProvider {
        provider_id: String,
    },
    RequestInference {
        agent_id: String,
        provider: String,
        model: String,
        messages_json: String,
        tools_json: String,
        max_tokens: u32,
        temperature: String,
        thinking_budget: u32,
        cache_control: u8,
        priority: u8,
        created_at: String,
    },
    ResetRateCounters,
    SetAgentBudget {
        agent_id: String,
        total_budget_tokens: u64,
        total_budget_usd: String,
        max_single_request_tokens: u64,
        updated_at: String,
    },
    SetApiKey {
        provider_id: String,
        api_key: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AppendStreamChunk { .. } => "append_stream_chunk",
            Reducer::CompleteInference { .. } => "complete_inference",
            Reducer::FailInference { .. } => "fail_inference",
            Reducer::RegisterProvider { .. } => "register_provider",
            Reducer::RemoveProvider { .. } => "remove_provider",
            Reducer::RequestInference { .. } => "request_inference",
            Reducer::ResetRateCounters => "reset_rate_counters",
            Reducer::SetAgentBudget { .. } => "set_agent_budget",
            Reducer::SetApiKey { .. } => "set_api_key",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AppendStreamChunk {
                request_id,
                agent_id,
                chunk_type,
                content,
                sequence,
                created_at,
            } => __sats::bsatn::to_vec(&append_stream_chunk_reducer::AppendStreamChunkArgs {
                request_id: request_id.clone(),
                agent_id: agent_id.clone(),
                chunk_type: chunk_type.clone(),
                content: content.clone(),
                sequence: sequence.clone(),
                created_at: created_at.clone(),
            }),
            Reducer::CompleteInference {
                request_id,
                content_json,
                model_used,
                input_tokens,
                output_tokens,
                cache_read_tokens,
                cache_write_tokens,
                latency_ms,
                cost_usd,
                openrouter_cost_usd,
                created_at,
            } => __sats::bsatn::to_vec(&complete_inference_reducer::CompleteInferenceArgs {
                request_id: request_id.clone(),
                content_json: content_json.clone(),
                model_used: model_used.clone(),
                input_tokens: input_tokens.clone(),
                output_tokens: output_tokens.clone(),
                cache_read_tokens: cache_read_tokens.clone(),
                cache_write_tokens: cache_write_tokens.clone(),
                latency_ms: latency_ms.clone(),
                cost_usd: cost_usd.clone(),
                openrouter_cost_usd: openrouter_cost_usd.clone(),
                created_at: created_at.clone(),
            }),
            Reducer::FailInference {
                request_id,
                error_message,
                created_at,
            } => __sats::bsatn::to_vec(&fail_inference_reducer::FailInferenceArgs {
                request_id: request_id.clone(),
                error_message: error_message.clone(),
                created_at: created_at.clone(),
            }),
            Reducer::RegisterProvider {
                provider_id,
                provider_type,
                base_url,
                api_key_ref,
                models_json,
                rate_limit_rpm,
                rate_limit_tpm,
                quantization_level,
                context_window,
                quality_score,
            } => __sats::bsatn::to_vec(&register_provider_reducer::RegisterProviderArgs {
                provider_id: provider_id.clone(),
                provider_type: provider_type.clone(),
                base_url: base_url.clone(),
                api_key_ref: api_key_ref.clone(),
                models_json: models_json.clone(),
                rate_limit_rpm: rate_limit_rpm.clone(),
                rate_limit_tpm: rate_limit_tpm.clone(),
                quantization_level: quantization_level.clone(),
                context_window: context_window.clone(),
                quality_score: quality_score.clone(),
            }),
            Reducer::RemoveProvider { provider_id } => {
                __sats::bsatn::to_vec(&remove_provider_reducer::RemoveProviderArgs {
                    provider_id: provider_id.clone(),
                })
            }
            Reducer::RequestInference {
                agent_id,
                provider,
                model,
                messages_json,
                tools_json,
                max_tokens,
                temperature,
                thinking_budget,
                cache_control,
                priority,
                created_at,
            } => __sats::bsatn::to_vec(&request_inference_reducer::RequestInferenceArgs {
                agent_id: agent_id.clone(),
                provider: provider.clone(),
                model: model.clone(),
                messages_json: messages_json.clone(),
                tools_json: tools_json.clone(),
                max_tokens: max_tokens.clone(),
                temperature: temperature.clone(),
                thinking_budget: thinking_budget.clone(),
                cache_control: cache_control.clone(),
                priority: priority.clone(),
                created_at: created_at.clone(),
            }),
            Reducer::ResetRateCounters => {
                __sats::bsatn::to_vec(&reset_rate_counters_reducer::ResetRateCountersArgs {})
            }
            Reducer::SetAgentBudget {
                agent_id,
                total_budget_tokens,
                total_budget_usd,
                max_single_request_tokens,
                updated_at,
            } => __sats::bsatn::to_vec(&set_agent_budget_reducer::SetAgentBudgetArgs {
                agent_id: agent_id.clone(),
                total_budget_tokens: total_budget_tokens.clone(),
                total_budget_usd: total_budget_usd.clone(),
                max_single_request_tokens: max_single_request_tokens.clone(),
                updated_at: updated_at.clone(),
            }),
            Reducer::SetApiKey { provider_id, api_key } => {
                __sats::bsatn::to_vec(&set_api_key_reducer::SetApiKeyArgs {
                    provider_id: provider_id.clone(),
                    api_key: api_key.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    agent_budget: __sdk::TableUpdate<AgentBudget>,
    inference_provider: __sdk::TableUpdate<InferenceProvider>,
    inference_request: __sdk::TableUpdate<InferenceRequest>,
    inference_response: __sdk::TableUpdate<InferenceResponse>,
    inference_stream_chunk: __sdk::TableUpdate<InferenceStreamChunk>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "agent_budget" => db_update
                    .agent_budget
                    .append(agent_budget_table::parse_table_update(table_update)?),
                "inference_provider" => db_update
                    .inference_provider
                    .append(inference_provider_table::parse_table_update(table_update)?),
                "inference_request" => db_update
                    .inference_request
                    .append(inference_request_table::parse_table_update(table_update)?),
                "inference_response" => db_update
                    .inference_response
                    .append(inference_response_table::parse_table_update(table_update)?),
                "inference_stream_chunk" => db_update.inference_stream_chunk.append(
                    inference_stream_chunk_table::parse_table_update(table_update)?,
                ),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.agent_budget = cache
            .apply_diff_to_table::<AgentBudget>("agent_budget", &self.agent_budget)
            .with_updates_by_pk(|row| &row.agent_id);
        diff.inference_provider = cache
            .apply_diff_to_table::<InferenceProvider>(
                "inference_provider",
                &self.inference_provider,
            )
            .with_updates_by_pk(|row| &row.provider_id);
        diff.inference_request = cache
            .apply_diff_to_table::<InferenceRequest>("inference_request", &self.inference_request)
            .with_updates_by_pk(|row| &row.request_id);
        diff.inference_response = cache
            .apply_diff_to_table::<InferenceResponse>(
                "inference_response",
                &self.inference_response,
            )
            .with_updates_by_pk(|row| &row.response_id);
        diff.inference_stream_chunk = cache
            .apply_diff_to_table::<InferenceStreamChunk>(
                "inference_stream_chunk",
                &self.inference_stream_chunk,
            )
            .with_updates_by_pk(|row| &row.chunk_id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "agent_budget" => db_update
                    .agent_budget
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inference_provider" => db_update
                    .inference_provider
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inference_request" => db_update
                    .inference_request
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inference_response" => db_update
                    .inference_response
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inference_stream_chunk" => db_update
                    .inference_stream_chunk
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "agent_budget" => db_update
                    .agent_budget
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inference_provider" => db_update
                    .inference_provider
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inference_request" => db_update
                    .inference_request
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inference_response" => db_update
                    .inference_response
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inference_stream_chunk" => db_update
                    .inference_stream_chunk
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    agent_budget: __sdk::TableAppliedDiff<'r, AgentBudget>,
    inference_provider: __sdk::TableAppliedDiff<'r, InferenceProvider>,
    inference_request: __sdk::TableAppliedDiff<'r, InferenceRequest>,
    inference_response: __sdk::TableAppliedDiff<'r, InferenceResponse>,
    inference_stream_chunk: __sdk::TableAppliedDiff<'r, InferenceStreamChunk>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AgentBudget>(
            "agent_budget",
            &self.agent_budget,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InferenceProvider>(
            "inference_provider",
            &self.inference_provider,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InferenceRequest>(
            "inference_request",
            &self.inference_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InferenceResponse>(
            "inference_response",
            &self.inference_response,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InferenceStreamChunk>(
            "inference_stream_chunk",
            &self.inference_stream_chunk,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        agent_budget_table::register_table(client_cache);
        inference_provider_table::register_table(client_cache);
        inference_request_table::register_table(client_cache);
        inference_response_table::register_table(client_cache);
        inference_stream_chunk_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "agent_budget",
        "inference_provider",
        "inference_request",
        "inference_response",
        "inference_stream_chunk",
    ];
}
