// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterProviderArgs {
    pub provider_id: String,
    pub provider_type: String,
    pub base_url: String,
    pub api_key_ref: String,
    pub models_json: String,
    pub rate_limit_rpm: u32,
    pub rate_limit_tpm: u64,
    pub quantization_level: String,
    pub context_window: u32,
    pub quality_score: f32,
}

impl From<RegisterProviderArgs> for super::Reducer {
    fn from(args: RegisterProviderArgs) -> Self {
        Self::RegisterProvider {
            provider_id: args.provider_id,
            provider_type: args.provider_type,
            base_url: args.base_url,
            api_key_ref: args.api_key_ref,
            models_json: args.models_json,
            rate_limit_rpm: args.rate_limit_rpm,
            rate_limit_tpm: args.rate_limit_tpm,
            quantization_level: args.quantization_level,
            context_window: args.context_window,
            quality_score: args.quality_score,
        }
    }
}

impl __sdk::InModule for RegisterProviderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_provider`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_provider {
    /// Request that the remote module invoke the reducer `register_provider` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_provider:register_provider_then`] to run a callback after the reducer completes.
    fn register_provider(
        &self,
        provider_id: String,
        provider_type: String,
        base_url: String,
        api_key_ref: String,
        models_json: String,
        rate_limit_rpm: u32,
        rate_limit_tpm: u64,
        quantization_level: String,
        context_window: u32,
        quality_score: f32,
    ) -> __sdk::Result<()> {
        self.register_provider_then(
            provider_id,
            provider_type,
            base_url,
            api_key_ref,
            models_json,
            rate_limit_rpm,
            rate_limit_tpm,
            quantization_level,
            context_window,
            quality_score,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_provider` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_provider_then(
        &self,
        provider_id: String,
        provider_type: String,
        base_url: String,
        api_key_ref: String,
        models_json: String,
        rate_limit_rpm: u32,
        rate_limit_tpm: u64,
        quantization_level: String,
        context_window: u32,
        quality_score: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_provider for super::RemoteReducers {
    fn register_provider_then(
        &self,
        provider_id: String,
        provider_type: String,
        base_url: String,
        api_key_ref: String,
        models_json: String,
        rate_limit_rpm: u32,
        rate_limit_tpm: u64,
        quantization_level: String,
        context_window: u32,
        quality_score: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterProviderArgs {
                provider_id,
                provider_type,
                base_url,
                api_key_ref,
                models_json,
                rate_limit_rpm,
                rate_limit_tpm,
                quantization_level,
                context_window,
                quality_score,
            },
            callback,
        )
    }
}
