// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveProviderArgs {
    pub provider_id: String,
}

impl From<RemoveProviderArgs> for super::Reducer {
    fn from(args: RemoveProviderArgs) -> Self {
        Self::RemoveProvider {
            provider_id: args.provider_id,
        }
    }
}

impl __sdk::InModule for RemoveProviderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_provider`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_provider {
    /// Request that the remote module invoke the reducer `remove_provider` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_provider:remove_provider_then`] to run a callback after the reducer completes.
    fn remove_provider(&self, provider_id: String) -> __sdk::Result<()> {
        self.remove_provider_then(provider_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_provider` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_provider_then(
        &self,
        provider_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_provider for super::RemoteReducers {
    fn remove_provider_then(
        &self,
        provider_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RemoveProviderArgs { provider_id }, callback)
    }
}
