#!/usr/bin/env bash
# Start script for Wire ConsoleAdapter to PrintHelloUseCase via composition-root
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
