#!/usr/bin/env bash
# Start script for Plan: build a simple Go REST API with gin framework that has CRUD endpoints for todos
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Fetching dependencies..."
go mod tidy

echo "Starting application..."
go run .
