// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentMessage {
    pub id: u64,
    pub from_agent: String,
    pub to_agent: Option::<String>,
    pub channel: Option::<String>,
    pub message: String,
    pub thread_id: Option::<String>,
    pub timestamp: String,
    pub read_by: Vec::<String>,
}


impl __sdk::InModule for AgentMessage {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `AgentMessage`.
///
/// Provides typed access to columns for query building.
pub struct AgentMessageCols {
    pub id: __sdk::__query_builder::Col<AgentMessage, u64>,
    pub from_agent: __sdk::__query_builder::Col<AgentMessage, String>,
    pub to_agent: __sdk::__query_builder::Col<AgentMessage, Option::<String>>,
    pub channel: __sdk::__query_builder::Col<AgentMessage, Option::<String>>,
    pub message: __sdk::__query_builder::Col<AgentMessage, String>,
    pub thread_id: __sdk::__query_builder::Col<AgentMessage, Option::<String>>,
    pub timestamp: __sdk::__query_builder::Col<AgentMessage, String>,
    pub read_by: __sdk::__query_builder::Col<AgentMessage, Vec::<String>>,
}

impl __sdk::__query_builder::HasCols for AgentMessage {
    type Cols = AgentMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentMessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            from_agent: __sdk::__query_builder::Col::new(table_name, "from_agent"),
            to_agent: __sdk::__query_builder::Col::new(table_name, "to_agent"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            thread_id: __sdk::__query_builder::Col::new(table_name, "thread_id"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            read_by: __sdk::__query_builder::Col::new(table_name, "read_by"),

        }
    }
}

/// Indexed column accessor struct for the table `AgentMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentMessageIxCols {
    pub id: __sdk::__query_builder::IxCol<AgentMessage, u64>,
}

impl __sdk::__query_builder::HasIxCols for AgentMessage {
    type IxCols = AgentMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentMessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentMessage {}

