// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::agent_typing_type::AgentTyping;

/// Table handle for the table `agent_typing`.
///
/// Obtain a handle from the [`AgentTypingTableAccess::agent_typing`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_typing()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_typing().on_insert(...)`.
pub struct AgentTypingTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentTyping>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_typing`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentTypingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentTypingTableHandle`], which mediates access to the table `agent_typing`.
    fn agent_typing(&self) -> AgentTypingTableHandle<'_>;
}

impl AgentTypingTableAccess for super::RemoteTables {
    fn agent_typing(&self) -> AgentTypingTableHandle<'_> {
        AgentTypingTableHandle {
            imp: self.imp.get_table::<AgentTyping>("agent_typing"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentTypingInsertCallbackId(__sdk::CallbackId);
pub struct AgentTypingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentTypingTableHandle<'ctx> {
    type Row = AgentTyping;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = AgentTyping> + '_ { self.imp.iter() }

    type InsertCallbackId = AgentTypingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentTypingInsertCallbackId {
        AgentTypingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentTypingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentTypingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentTypingDeleteCallbackId {
        AgentTypingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentTypingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

        /// Access to the `agent` unique index on the table `agent_typing`,
        /// which allows point queries on the field of the same name
        /// via the [`AgentTypingAgentUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.agent_typing().agent().find(...)`.
        pub struct AgentTypingAgentUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<AgentTyping, String>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> AgentTypingTableHandle<'ctx> {
            /// Get a handle on the `agent` unique index on the table `agent_typing`.
            pub fn agent(&self) -> AgentTypingAgentUnique<'ctx> {
                AgentTypingAgentUnique {
                    imp: self.imp.get_unique_constraint::<String>("agent"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> AgentTypingAgentUnique<'ctx> {
            /// Find the subscribed row whose `agent` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &String) -> Option<AgentTyping> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<AgentTyping>("agent_typing");
    _table.add_unique_constraint::<String>("agent", |row| &row.agent);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentTyping>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<AgentTyping>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `AgentTyping`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait agent_typingQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `AgentTyping`.
            fn agent_typing(&self) -> __sdk::__query_builder::Table<AgentTyping>;
        }

        impl agent_typingQueryTableAccess for __sdk::QueryTableAccessor {
            fn agent_typing(&self) -> __sdk::__query_builder::Table<AgentTyping> {
                __sdk::__query_builder::Table::new("agent_typing")
            }
        }

