// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::agent_message_type::AgentMessage;

/// Table handle for the table `agent_messages`.
///
/// Obtain a handle from the [`AgentMessagesTableAccess::agent_messages`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_messages()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_messages().on_insert(...)`.
pub struct AgentMessagesTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_messages`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentMessagesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentMessagesTableHandle`], which mediates access to the table `agent_messages`.
    fn agent_messages(&self) -> AgentMessagesTableHandle<'_>;
}

impl AgentMessagesTableAccess for super::RemoteTables {
    fn agent_messages(&self) -> AgentMessagesTableHandle<'_> {
        AgentMessagesTableHandle {
            imp: self.imp.get_table::<AgentMessage>("agent_messages"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentMessagesInsertCallbackId(__sdk::CallbackId);
pub struct AgentMessagesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentMessagesTableHandle<'ctx> {
    type Row = AgentMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = AgentMessage> + '_ { self.imp.iter() }

    type InsertCallbackId = AgentMessagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentMessagesInsertCallbackId {
        AgentMessagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentMessagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentMessagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentMessagesDeleteCallbackId {
        AgentMessagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentMessagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentMessagesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentMessagesTableHandle<'ctx> {
    type UpdateCallbackId = AgentMessagesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentMessagesUpdateCallbackId {
        AgentMessagesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentMessagesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `agent_messages`,
        /// which allows point queries on the field of the same name
        /// via the [`AgentMessagesIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.agent_messages().id().find(...)`.
        pub struct AgentMessagesIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<AgentMessage, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> AgentMessagesTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `agent_messages`.
            pub fn id(&self) -> AgentMessagesIdUnique<'ctx> {
                AgentMessagesIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> AgentMessagesIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<AgentMessage> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<AgentMessage>("agent_messages");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<AgentMessage>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `AgentMessage`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait agent_messagesQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `AgentMessage`.
            fn agent_messages(&self) -> __sdk::__query_builder::Table<AgentMessage>;
        }

        impl agent_messagesQueryTableAccess for __sdk::QueryTableAccessor {
            fn agent_messages(&self) -> __sdk::__query_builder::Table<AgentMessage> {
                __sdk::__query_builder::Table::new("agent_messages")
            }
        }

