// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentChannel {
    pub name: String,
    pub members: Vec::<String>,
    pub created_at: String,
}


impl __sdk::InModule for AgentChannel {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `AgentChannel`.
///
/// Provides typed access to columns for query building.
pub struct AgentChannelCols {
    pub name: __sdk::__query_builder::Col<AgentChannel, String>,
    pub members: __sdk::__query_builder::Col<AgentChannel, Vec::<String>>,
    pub created_at: __sdk::__query_builder::Col<AgentChannel, String>,
}

impl __sdk::__query_builder::HasCols for AgentChannel {
    type Cols = AgentChannelCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentChannelCols {
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            members: __sdk::__query_builder::Col::new(table_name, "members"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),

        }
    }
}

/// Indexed column accessor struct for the table `AgentChannel`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentChannelIxCols {
    pub name: __sdk::__query_builder::IxCol<AgentChannel, String>,
}

impl __sdk::__query_builder::HasIxCols for AgentChannel {
    type IxCols = AgentChannelIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentChannelIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentChannel {}

