// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::agent_channel_type::AgentChannel;

/// Table handle for the table `agent_channels`.
///
/// Obtain a handle from the [`AgentChannelsTableAccess::agent_channels`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_channels()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_channels().on_insert(...)`.
pub struct AgentChannelsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentChannel>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_channels`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentChannelsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentChannelsTableHandle`], which mediates access to the table `agent_channels`.
    fn agent_channels(&self) -> AgentChannelsTableHandle<'_>;
}

impl AgentChannelsTableAccess for super::RemoteTables {
    fn agent_channels(&self) -> AgentChannelsTableHandle<'_> {
        AgentChannelsTableHandle {
            imp: self.imp.get_table::<AgentChannel>("agent_channels"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentChannelsInsertCallbackId(__sdk::CallbackId);
pub struct AgentChannelsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentChannelsTableHandle<'ctx> {
    type Row = AgentChannel;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = AgentChannel> + '_ { self.imp.iter() }

    type InsertCallbackId = AgentChannelsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentChannelsInsertCallbackId {
        AgentChannelsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentChannelsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentChannelsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentChannelsDeleteCallbackId {
        AgentChannelsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentChannelsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

        /// Access to the `name` unique index on the table `agent_channels`,
        /// which allows point queries on the field of the same name
        /// via the [`AgentChannelsNameUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.agent_channels().name().find(...)`.
        pub struct AgentChannelsNameUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<AgentChannel, String>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> AgentChannelsTableHandle<'ctx> {
            /// Get a handle on the `name` unique index on the table `agent_channels`.
            pub fn name(&self) -> AgentChannelsNameUnique<'ctx> {
                AgentChannelsNameUnique {
                    imp: self.imp.get_unique_constraint::<String>("name"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> AgentChannelsNameUnique<'ctx> {
            /// Find the subscribed row whose `name` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &String) -> Option<AgentChannel> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<AgentChannel>("agent_channels");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentChannel>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<AgentChannel>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `AgentChannel`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait agent_channelsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `AgentChannel`.
            fn agent_channels(&self) -> __sdk::__query_builder::Table<AgentChannel>;
        }

        impl agent_channelsQueryTableAccess for __sdk::QueryTableAccessor {
            fn agent_channels(&self) -> __sdk::__query_builder::Table<AgentChannel> {
                __sdk::__query_builder::Table::new("agent_channels")
            }
        }

