// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendToChannelArgs {
    pub from: String,
    pub channel: String,
    pub message: String,
    pub thread_id: Option::<String>,
}

impl From<SendToChannelArgs> for super::Reducer {
    fn from(args: SendToChannelArgs) -> Self {
        Self::SendToChannel {
            from: args.from,
            channel: args.channel,
            message: args.message,
            thread_id: args.thread_id,
}
}
}

impl __sdk::InModule for SendToChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_to_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_to_channel {
    /// Request that the remote module invoke the reducer `send_to_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_to_channel:send_to_channel_then`] to run a callback after the reducer completes.
    fn send_to_channel(&self, from: String,
channel: String,
message: String,
thread_id: Option::<String>,
) -> __sdk::Result<()> {
        self.send_to_channel_then(from, channel, message, thread_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_to_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_to_channel_then(
        &self,
        from: String,
channel: String,
message: String,
thread_id: Option::<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl send_to_channel for super::RemoteReducers {
    fn send_to_channel_then(
        &self,
        from: String,
channel: String,
message: String,
thread_id: Option::<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SendToChannelArgs { from, channel, message, thread_id,  }, callback)
    }
}

