// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DecayPatternsArgs {}

impl From<DecayPatternsArgs> for super::Reducer {
    fn from(args: DecayPatternsArgs) -> Self {
        Self::DecayPatterns
    }
}

impl __sdk::InModule for DecayPatternsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decay_patterns`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decay_patterns {
    /// Request that the remote module invoke the reducer `decay_patterns` to run as soon as possible.
    fn decay_patterns(&self) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `decay_patterns`.
    fn on_decay_patterns(&self, callback: impl FnMut(&super::ReducerEventContext, &DecayPatternsArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_decay_patterns(&self, callback: __sdk::CallbackId);
}

impl decay_patterns for super::RemoteReducers {
    fn decay_patterns(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("decay_patterns", DecayPatternsArgs {  })
    }

    fn on_decay_patterns(&self, mut callback: impl FnMut(&super::ReducerEventContext, &DecayPatternsArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("decay_patterns", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::DecayPatterns {  } = &ctx.event.reducer else { unreachable!() };
            let args = DecayPatternsArgs {  };
            callback(ctx, &args);
        }))
    }

    fn remove_on_decay_patterns(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("decay_patterns", callback);
    }
}
