// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RlExperience {
    pub id: String,
    pub state_key: String,
    pub action: String,
    pub reward: f64,
    pub next_state_key: String,
    pub task_type: String,
    pub timestamp: String,
}

impl __sdk::InModule for RlExperience {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RlExperience`.
///
/// Provides typed access to columns for query building.
pub struct RlExperienceCols {
    pub id: __sdk::__query_builder::Col<RlExperience, String>,
    pub state_key: __sdk::__query_builder::Col<RlExperience, String>,
    pub action: __sdk::__query_builder::Col<RlExperience, String>,
    pub reward: __sdk::__query_builder::Col<RlExperience, f64>,
    pub next_state_key: __sdk::__query_builder::Col<RlExperience, String>,
    pub task_type: __sdk::__query_builder::Col<RlExperience, String>,
    pub timestamp: __sdk::__query_builder::Col<RlExperience, String>,
}

impl __sdk::__query_builder::HasCols for RlExperience {
    type Cols = RlExperienceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RlExperienceCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            state_key: __sdk::__query_builder::Col::new(table_name, "state_key"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            reward: __sdk::__query_builder::Col::new(table_name, "reward"),
            next_state_key: __sdk::__query_builder::Col::new(table_name, "next_state_key"),
            task_type: __sdk::__query_builder::Col::new(table_name, "task_type"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `RlExperience`.
///
/// Provides typed access to indexed columns for query building.
pub struct RlExperienceIxCols {
    pub id: __sdk::__query_builder::IxCol<RlExperience, String>,
}

impl __sdk::__query_builder::HasIxCols for RlExperience {
    type IxCols = RlExperienceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RlExperienceIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

