// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RlPattern {
    pub id: String,
    pub category: String,
    pub content: String,
    pub confidence: f64,
    pub created_at: String,
    pub last_accessed: String,
    pub access_count: u32,
    pub decay_rate: f64,
}

impl __sdk::InModule for RlPattern {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RlPattern`.
///
/// Provides typed access to columns for query building.
pub struct RlPatternCols {
    pub id: __sdk::__query_builder::Col<RlPattern, String>,
    pub category: __sdk::__query_builder::Col<RlPattern, String>,
    pub content: __sdk::__query_builder::Col<RlPattern, String>,
    pub confidence: __sdk::__query_builder::Col<RlPattern, f64>,
    pub created_at: __sdk::__query_builder::Col<RlPattern, String>,
    pub last_accessed: __sdk::__query_builder::Col<RlPattern, String>,
    pub access_count: __sdk::__query_builder::Col<RlPattern, u32>,
    pub decay_rate: __sdk::__query_builder::Col<RlPattern, f64>,
}

impl __sdk::__query_builder::HasCols for RlPattern {
    type Cols = RlPatternCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RlPatternCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            confidence: __sdk::__query_builder::Col::new(table_name, "confidence"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_accessed: __sdk::__query_builder::Col::new(table_name, "last_accessed"),
            access_count: __sdk::__query_builder::Col::new(table_name, "access_count"),
            decay_rate: __sdk::__query_builder::Col::new(table_name, "decay_rate"),
        }
    }
}

/// Indexed column accessor struct for the table `RlPattern`.
///
/// Provides typed access to indexed columns for query building.
pub struct RlPatternIxCols {
    pub id: __sdk::__query_builder::IxCol<RlPattern, String>,
}

impl __sdk::__query_builder::HasIxCols for RlPattern {
    type IxCols = RlPatternIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RlPatternIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

