// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RlQEntry {
    pub composite_id: String,
    pub state_key: String,
    pub action: String,
    pub q_value: f64,
    pub visit_count: u32,
    pub last_updated: String,
}

impl __sdk::InModule for RlQEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RlQEntry`.
///
/// Provides typed access to columns for query building.
pub struct RlQEntryCols {
    pub composite_id: __sdk::__query_builder::Col<RlQEntry, String>,
    pub state_key: __sdk::__query_builder::Col<RlQEntry, String>,
    pub action: __sdk::__query_builder::Col<RlQEntry, String>,
    pub q_value: __sdk::__query_builder::Col<RlQEntry, f64>,
    pub visit_count: __sdk::__query_builder::Col<RlQEntry, u32>,
    pub last_updated: __sdk::__query_builder::Col<RlQEntry, String>,
}

impl __sdk::__query_builder::HasCols for RlQEntry {
    type Cols = RlQEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RlQEntryCols {
            composite_id: __sdk::__query_builder::Col::new(table_name, "composite_id"),
            state_key: __sdk::__query_builder::Col::new(table_name, "state_key"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            q_value: __sdk::__query_builder::Col::new(table_name, "q_value"),
            visit_count: __sdk::__query_builder::Col::new(table_name, "visit_count"),
            last_updated: __sdk::__query_builder::Col::new(table_name, "last_updated"),
        }
    }
}

/// Indexed column accessor struct for the table `RlQEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct RlQEntryIxCols {
    pub composite_id: __sdk::__query_builder::IxCol<RlQEntry, String>,
}

impl __sdk::__query_builder::HasIxCols for RlQEntry {
    type IxCols = RlQEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RlQEntryIxCols {
            composite_id: __sdk::__query_builder::IxCol::new(table_name, "composite_id"),
        }
    }
}

