// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rl_q_entry_type::RlQEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rl_q_entry`.
///
/// Obtain a handle from the [`RlQEntryTableAccess::rl_q_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.rl_q_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rl_q_entry().on_insert(...)`.
pub struct RlQEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<RlQEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rl_q_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RlQEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RlQEntryTableHandle`], which mediates access to the table `rl_q_entry`.
    fn rl_q_entry(&self) -> RlQEntryTableHandle<'_>;
}

impl RlQEntryTableAccess for super::RemoteTables {
    fn rl_q_entry(&self) -> RlQEntryTableHandle<'_> {
        RlQEntryTableHandle {
            imp: self.imp.get_table::<RlQEntry>("rl_q_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RlQEntryInsertCallbackId(__sdk::CallbackId);
pub struct RlQEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RlQEntryTableHandle<'ctx> {
    type Row = RlQEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RlQEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RlQEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RlQEntryInsertCallbackId {
        RlQEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RlQEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RlQEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RlQEntryDeleteCallbackId {
        RlQEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RlQEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `composite_id` unique index on the table `rl_q_entry`,
/// which allows point queries on the field of the same name
/// via the [`RlQEntryCompositeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rl_q_entry().composite_id().find(...)`.
pub struct RlQEntryCompositeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RlQEntry, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RlQEntryTableHandle<'ctx> {
    /// Get a handle on the `composite_id` unique index on the table `rl_q_entry`.
    pub fn composite_id(&self) -> RlQEntryCompositeIdUnique<'ctx> {
        RlQEntryCompositeIdUnique {
            imp: self.imp.get_unique_constraint::<String>("composite_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RlQEntryCompositeIdUnique<'ctx> {
    /// Find the subscribed row whose `composite_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RlQEntry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RlQEntry>("rl_q_entry");
    _table.add_unique_constraint::<String>("composite_id", |row| &row.composite_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RlQEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RlQEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RlQEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait rl_q_entryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RlQEntry`.
    fn rl_q_entry(&self) -> __sdk::__query_builder::Table<RlQEntry>;
}

impl rl_q_entryQueryTableAccess for __sdk::QueryTableAccessor {
    fn rl_q_entry(&self) -> __sdk::__query_builder::Table<RlQEntry> {
        __sdk::__query_builder::Table::new("rl_q_entry")
    }
}
