// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rl_pattern_type::RlPattern;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rl_pattern`.
///
/// Obtain a handle from the [`RlPatternTableAccess::rl_pattern`] method on [`super::RemoteTables`],
/// like `ctx.db.rl_pattern()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rl_pattern().on_insert(...)`.
pub struct RlPatternTableHandle<'ctx> {
    imp: __sdk::TableHandle<RlPattern>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rl_pattern`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RlPatternTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RlPatternTableHandle`], which mediates access to the table `rl_pattern`.
    fn rl_pattern(&self) -> RlPatternTableHandle<'_>;
}

impl RlPatternTableAccess for super::RemoteTables {
    fn rl_pattern(&self) -> RlPatternTableHandle<'_> {
        RlPatternTableHandle {
            imp: self.imp.get_table::<RlPattern>("rl_pattern"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RlPatternInsertCallbackId(__sdk::CallbackId);
pub struct RlPatternDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RlPatternTableHandle<'ctx> {
    type Row = RlPattern;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RlPattern> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RlPatternInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RlPatternInsertCallbackId {
        RlPatternInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RlPatternInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RlPatternDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RlPatternDeleteCallbackId {
        RlPatternDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RlPatternDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `id` unique index on the table `rl_pattern`,
/// which allows point queries on the field of the same name
/// via the [`RlPatternIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rl_pattern().id().find(...)`.
pub struct RlPatternIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RlPattern, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RlPatternTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rl_pattern`.
    pub fn id(&self) -> RlPatternIdUnique<'ctx> {
        RlPatternIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RlPatternIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RlPattern> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RlPattern>("rl_pattern");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RlPattern>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RlPattern>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RlPattern`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait rl_patternQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RlPattern`.
    fn rl_pattern(&self) -> __sdk::__query_builder::Table<RlPattern>;
}

impl rl_patternQueryTableAccess for __sdk::QueryTableAccessor {
    fn rl_pattern(&self) -> __sdk::__query_builder::Table<RlPattern> {
        __sdk::__query_builder::Table::new("rl_pattern")
    }
}
