// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StorePatternArgs {
    pub category: String,
    pub content: String,
    pub confidence: f64,
}

impl From<StorePatternArgs> for super::Reducer {
    fn from(args: StorePatternArgs) -> Self {
        Self::StorePattern {
            category: args.category,
            content: args.content,
            confidence: args.confidence,
        }
    }
}

impl __sdk::InModule for StorePatternArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `store_pattern`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait store_pattern {
    /// Request that the remote module invoke the reducer `store_pattern` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`store_pattern:store_pattern_then`] to run a callback after the reducer completes.
    fn store_pattern(
        &self,
        category: String,
        content: String,
        confidence: f64,
    ) -> __sdk::Result<()> {
        self.store_pattern_then(category, content, confidence, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `store_pattern` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn store_pattern_then(
        &self,
        category: String,
        content: String,
        confidence: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl store_pattern for super::RemoteReducers {
    fn store_pattern_then(
        &self,
        category: String,
        content: String,
        confidence: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StorePatternArgs {
                category,
                content,
                confidence,
            },
            callback,
        )
    }
}
