// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Agent {
    pub id: String,
    pub name: String,
    pub project_dir: String,
    pub model: String,
    pub status: String,
    pub started_at: String,
    pub ended_at: String,
    pub metrics_json: String,
}

impl __sdk::InModule for Agent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Agent`.
///
/// Provides typed access to columns for query building.
pub struct AgentCols {
    pub id: __sdk::__query_builder::Col<Agent, String>,
    pub name: __sdk::__query_builder::Col<Agent, String>,
    pub project_dir: __sdk::__query_builder::Col<Agent, String>,
    pub model: __sdk::__query_builder::Col<Agent, String>,
    pub status: __sdk::__query_builder::Col<Agent, String>,
    pub started_at: __sdk::__query_builder::Col<Agent, String>,
    pub ended_at: __sdk::__query_builder::Col<Agent, String>,
    pub metrics_json: __sdk::__query_builder::Col<Agent, String>,
}

impl __sdk::__query_builder::HasCols for Agent {
    type Cols = AgentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            project_dir: __sdk::__query_builder::Col::new(table_name, "project_dir"),
            model: __sdk::__query_builder::Col::new(table_name, "model"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            ended_at: __sdk::__query_builder::Col::new(table_name, "ended_at"),
            metrics_json: __sdk::__query_builder::Col::new(table_name, "metrics_json"),
        }
    }
}

/// Indexed column accessor struct for the table `Agent`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentIxCols {
    pub id: __sdk::__query_builder::IxCol<Agent, String>,
}

impl __sdk::__query_builder::HasIxCols for Agent {
    type IxCols = AgentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

