// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_heartbeat_type::AgentHeartbeat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_heartbeat`.
///
/// Obtain a handle from the [`AgentHeartbeatTableAccess::agent_heartbeat`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_heartbeat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_heartbeat().on_insert(...)`.
pub struct AgentHeartbeatTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentHeartbeat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_heartbeat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentHeartbeatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentHeartbeatTableHandle`], which mediates access to the table `agent_heartbeat`.
    fn agent_heartbeat(&self) -> AgentHeartbeatTableHandle<'_>;
}

impl AgentHeartbeatTableAccess for super::RemoteTables {
    fn agent_heartbeat(&self) -> AgentHeartbeatTableHandle<'_> {
        AgentHeartbeatTableHandle {
            imp: self.imp.get_table::<AgentHeartbeat>("agent_heartbeat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentHeartbeatInsertCallbackId(__sdk::CallbackId);
pub struct AgentHeartbeatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentHeartbeatTableHandle<'ctx> {
    type Row = AgentHeartbeat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentHeartbeat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentHeartbeatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatInsertCallbackId {
        AgentHeartbeatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentHeartbeatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentHeartbeatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentHeartbeatDeleteCallbackId {
        AgentHeartbeatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentHeartbeatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `agent_heartbeat`,
/// which allows point queries on the field of the same name
/// via the [`AgentHeartbeatAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_heartbeat().agent_id().find(...)`.
pub struct AgentHeartbeatAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentHeartbeat, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentHeartbeatTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `agent_heartbeat`.
    pub fn agent_id(&self) -> AgentHeartbeatAgentIdUnique<'ctx> {
        AgentHeartbeatAgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentHeartbeatAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgentHeartbeat> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentHeartbeat>("agent_heartbeat");
    _table.add_unique_constraint::<String>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentHeartbeat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentHeartbeat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentHeartbeat`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_heartbeatQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentHeartbeat`.
    fn agent_heartbeat(&self) -> __sdk::__query_builder::Table<AgentHeartbeat>;
}

impl agent_heartbeatQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_heartbeat(&self) -> __sdk::__query_builder::Table<AgentHeartbeat> {
        __sdk::__query_builder::Table::new("agent_heartbeat")
    }
}
