// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveAgentArgs {
    pub id: String,
}

impl From<RemoveAgentArgs> for super::Reducer {
    fn from(args: RemoveAgentArgs) -> Self {
        Self::RemoveAgent { id: args.id }
    }
}

impl __sdk::InModule for RemoveAgentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_agent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_agent {
    /// Request that the remote module invoke the reducer `remove_agent` to run as soon as possible.
    fn remove_agent(&self, id: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `remove_agent`.
    fn on_remove_agent(&self, callback: impl FnMut(&super::ReducerEventContext, &RemoveAgentArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_remove_agent(&self, callback: __sdk::CallbackId);
}

impl remove_agent for super::RemoteReducers {
    fn remove_agent(&self, id: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("remove_agent", RemoveAgentArgs { id })
    }

    fn on_remove_agent(&self, mut callback: impl FnMut(&super::ReducerEventContext, &RemoveAgentArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("remove_agent", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::RemoveAgent { id } = &ctx.event.reducer else { unreachable!() };
            let args = RemoveAgentArgs { id: id.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_remove_agent(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("remove_agent", callback);
    }
}
