// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateStatusArgs {
    pub id: String,
    pub status: String,
    pub metrics_json: String,
}

impl From<UpdateStatusArgs> for super::Reducer {
    fn from(args: UpdateStatusArgs) -> Self {
        Self::UpdateStatus {
            id: args.id,
            status: args.status,
            metrics_json: args.metrics_json,
        }
    }
}

impl __sdk::InModule for UpdateStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_status {
    /// Request that the remote module invoke the reducer `update_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_status:update_status_then`] to run a callback after the reducer completes.
    fn update_status(&self, id: String, status: String, metrics_json: String) -> __sdk::Result<()> {
        self.update_status_then(id, status, metrics_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_status_then(
        &self,
        id: String,
        status: String,
        metrics_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_status for super::RemoteReducers {
    fn update_status_then(
        &self,
        id: String,
        status: String,
        metrics_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateStatusArgs {
                id,
                status,
                metrics_json,
            },
            callback,
        )
    }
}
