// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateStatusArgs {
    pub id: String,
    pub status: String,
    pub metrics_json: String,
}

impl From<UpdateStatusArgs> for super::Reducer {
    fn from(args: UpdateStatusArgs) -> Self {
        Self::UpdateStatus {
            id: args.id,
            status: args.status,
            metrics_json: args.metrics_json,
        }
    }
}

impl __sdk::InModule for UpdateStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_status {
    /// Request that the remote module invoke the reducer `update_status` to run as soon as possible.
    fn update_status(&self, id: String, status: String, metrics_json: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_status`.
    fn on_update_status(&self, callback: impl FnMut(&super::ReducerEventContext, &UpdateStatusArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_update_status(&self, callback: __sdk::CallbackId);
}

impl update_status for super::RemoteReducers {
    fn update_status(&self, id: String, status: String, metrics_json: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("update_status", UpdateStatusArgs { id, status, metrics_json })
    }

    fn on_update_status(&self, mut callback: impl FnMut(&super::ReducerEventContext, &UpdateStatusArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("update_status", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::UpdateStatus { id, status, metrics_json } = &ctx.event.reducer else { unreachable!() };
            let args = UpdateStatusArgs { id: id.clone(), status: status.clone(), metrics_json: metrics_json.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_update_status(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("update_status", callback);
    }
}
