// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  id: __t.string(),
  name: __t.string(),
  projectDir: __t.string(),
  model: __t.string(),
  status: __t.string(),
  startedAt: __t.string(),
  endedAt: __t.string(),
  metricsJson: __t.string(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentHeartbeat = __t.object("AgentHeartbeat", {
  agentId: __t.string(),
  lastSeen: __t.string(),
  turnCount: __t.u32(),
  tokenUsage: __t.u64(),
});
export type AgentHeartbeat = __Infer<typeof AgentHeartbeat>;

