#!/usr/bin/env bash
# Start script for Financial Services Portfolio Management Platform
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
bun install 2>/dev/null || npm install

echo "Starting application..."
bun run start
