#!/usr/bin/env bash
# Start script for Build URL Shortener REST API in Go with In-Memory Storage
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Fetching dependencies..."
go mod tidy

echo "Starting application..."
go run .
