#!/usr/bin/env bash
# Start script for Plan: P1.3: Update composition root to inject Ergast adapter into use cases
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
