#!/usr/bin/env bash
# Start script for Plan: P3.1: Compose CLI with FizzBuzz port in composition root
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
