// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  username: __t.string(),
  status: __t.string(),
  maxAgents: __t.u32().name("max_agents"),
  activeAgents: __t.u32().name("active_agents"),
  lastHealthCheck: __t.string().name("last_health_check"),
});
