// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::workplan_task_type::WorkplanTask;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `workplan_task`.
///
/// Obtain a handle from the [`WorkplanTaskTableAccess::workplan_task`] method on [`super::RemoteTables`],
/// like `ctx.db.workplan_task()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workplan_task().on_insert(...)`.
pub struct WorkplanTaskTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorkplanTask>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workplan_task`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkplanTaskTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkplanTaskTableHandle`], which mediates access to the table `workplan_task`.
    fn workplan_task(&self) -> WorkplanTaskTableHandle<'_>;
}

impl WorkplanTaskTableAccess for super::RemoteTables {
    fn workplan_task(&self) -> WorkplanTaskTableHandle<'_> {
        WorkplanTaskTableHandle {
            imp: self.imp.get_table::<WorkplanTask>("workplan_task"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkplanTaskInsertCallbackId(__sdk::CallbackId);
pub struct WorkplanTaskDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkplanTaskTableHandle<'ctx> {
    type Row = WorkplanTask;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorkplanTask> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorkplanTaskInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkplanTaskInsertCallbackId {
        WorkplanTaskInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkplanTaskInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkplanTaskDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkplanTaskDeleteCallbackId {
        WorkplanTaskDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkplanTaskDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `id` unique index on the table `workplan_task`,
/// which allows point queries on the field of the same name
/// via the [`WorkplanTaskIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workplan_task().id().find(...)`.
pub struct WorkplanTaskIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorkplanTask, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorkplanTaskTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `workplan_task`.
    pub fn id(&self) -> WorkplanTaskIdUnique<'ctx> {
        WorkplanTaskIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorkplanTaskIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<WorkplanTask> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorkplanTask>("workplan_task");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorkplanTask>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorkplanTask>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorkplanTask`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait workplan_taskQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorkplanTask`.
    fn workplan_task(&self) -> __sdk::__query_builder::Table<WorkplanTask>;
}

impl workplan_taskQueryTableAccess for __sdk::QueryTableAccessor {
    fn workplan_task(&self) -> __sdk::__query_builder::Table<WorkplanTask> {
        __sdk::__query_builder::Table::new("workplan_task")
    }
}
