// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::workplan_execution_type::WorkplanExecution;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `workplan_execution`.
///
/// Obtain a handle from the [`WorkplanExecutionTableAccess::workplan_execution`] method on [`super::RemoteTables`],
/// like `ctx.db.workplan_execution()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workplan_execution().on_insert(...)`.
pub struct WorkplanExecutionTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorkplanExecution>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workplan_execution`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkplanExecutionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkplanExecutionTableHandle`], which mediates access to the table `workplan_execution`.
    fn workplan_execution(&self) -> WorkplanExecutionTableHandle<'_>;
}

impl WorkplanExecutionTableAccess for super::RemoteTables {
    fn workplan_execution(&self) -> WorkplanExecutionTableHandle<'_> {
        WorkplanExecutionTableHandle {
            imp: self
                .imp
                .get_table::<WorkplanExecution>("workplan_execution"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkplanExecutionInsertCallbackId(__sdk::CallbackId);
pub struct WorkplanExecutionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkplanExecutionTableHandle<'ctx> {
    type Row = WorkplanExecution;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorkplanExecution> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorkplanExecutionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkplanExecutionInsertCallbackId {
        WorkplanExecutionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkplanExecutionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkplanExecutionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkplanExecutionDeleteCallbackId {
        WorkplanExecutionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkplanExecutionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `id` unique index on the table `workplan_execution`,
/// which allows point queries on the field of the same name
/// via the [`WorkplanExecutionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workplan_execution().id().find(...)`.
pub struct WorkplanExecutionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorkplanExecution, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorkplanExecutionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `workplan_execution`.
    pub fn id(&self) -> WorkplanExecutionIdUnique<'ctx> {
        WorkplanExecutionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorkplanExecutionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<WorkplanExecution> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorkplanExecution>("workplan_execution");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WorkplanExecution>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorkplanExecution>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorkplanExecution`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait workplan_executionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorkplanExecution`.
    fn workplan_execution(&self) -> __sdk::__query_builder::Table<WorkplanExecution>;
}

impl workplan_executionQueryTableAccess for __sdk::QueryTableAccessor {
    fn workplan_execution(&self) -> __sdk::__query_builder::Table<WorkplanExecution> {
        __sdk::__query_builder::Table::new("workplan_execution")
    }
}
