// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HookExecutionLog {
    pub hook_id: String,
    pub agent_id: String,
    pub event_type: String,
    pub exit_code: i32,
    pub stdout: String,
    pub stderr: String,
    pub duration_ms: u64,
    pub timed_out: bool,
    pub timestamp: String,
}

impl __sdk::InModule for HookExecutionLog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HookExecutionLog`.
///
/// Provides typed access to columns for query building.
pub struct HookExecutionLogCols {
    pub hook_id: __sdk::__query_builder::Col<HookExecutionLog, String>,
    pub agent_id: __sdk::__query_builder::Col<HookExecutionLog, String>,
    pub event_type: __sdk::__query_builder::Col<HookExecutionLog, String>,
    pub exit_code: __sdk::__query_builder::Col<HookExecutionLog, i32>,
    pub stdout: __sdk::__query_builder::Col<HookExecutionLog, String>,
    pub stderr: __sdk::__query_builder::Col<HookExecutionLog, String>,
    pub duration_ms: __sdk::__query_builder::Col<HookExecutionLog, u64>,
    pub timed_out: __sdk::__query_builder::Col<HookExecutionLog, bool>,
    pub timestamp: __sdk::__query_builder::Col<HookExecutionLog, String>,
}

impl __sdk::__query_builder::HasCols for HookExecutionLog {
    type Cols = HookExecutionLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HookExecutionLogCols {
            hook_id: __sdk::__query_builder::Col::new(table_name, "hook_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            exit_code: __sdk::__query_builder::Col::new(table_name, "exit_code"),
            stdout: __sdk::__query_builder::Col::new(table_name, "stdout"),
            stderr: __sdk::__query_builder::Col::new(table_name, "stderr"),
            duration_ms: __sdk::__query_builder::Col::new(table_name, "duration_ms"),
            timed_out: __sdk::__query_builder::Col::new(table_name, "timed_out"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `HookExecutionLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct HookExecutionLogIxCols {}

impl __sdk::__query_builder::HasIxCols for HookExecutionLog {
    type IxCols = HookExecutionLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HookExecutionLogIxCols {}
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HookExecutionLog {}
