// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LogExecutionArgs {
    pub hook_id: String,
    pub agent_id: String,
    pub event_type: String,
    pub exit_code: i32,
    pub stdout: String,
    pub stderr: String,
    pub duration_ms: u64,
    pub timed_out: bool,
    pub timestamp: String,
}

impl From<LogExecutionArgs> for super::Reducer {
    fn from(args: LogExecutionArgs) -> Self {
        Self::LogExecution {
            hook_id: args.hook_id,
            agent_id: args.agent_id,
            event_type: args.event_type,
            exit_code: args.exit_code,
            stdout: args.stdout,
            stderr: args.stderr,
            duration_ms: args.duration_ms,
            timed_out: args.timed_out,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for LogExecutionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `log_execution`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait log_execution {
    /// Request that the remote module invoke the reducer `log_execution` to run as soon as possible.
    fn log_execution(&self, hook_id: String, agent_id: String, event_type: String, exit_code: i32, stdout: String, stderr: String, duration_ms: u64, timed_out: bool, timestamp: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `log_execution`.
    fn on_log_execution(&self, callback: impl FnMut(&super::ReducerEventContext, &LogExecutionArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_log_execution(&self, callback: __sdk::CallbackId);
}

impl log_execution for super::RemoteReducers {
    fn log_execution(&self, hook_id: String, agent_id: String, event_type: String, exit_code: i32, stdout: String, stderr: String, duration_ms: u64, timed_out: bool, timestamp: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("log_execution", LogExecutionArgs { hook_id, agent_id, event_type, exit_code, stdout, stderr, duration_ms, timed_out, timestamp })
    }

    fn on_log_execution(&self, mut callback: impl FnMut(&super::ReducerEventContext, &LogExecutionArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("log_execution", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::LogExecution { hook_id, agent_id, event_type, exit_code, stdout, stderr, duration_ms, timed_out, timestamp } = &ctx.event.reducer else { unreachable!() };
            let args = LogExecutionArgs { hook_id: hook_id.clone(), agent_id: agent_id.clone(), event_type: event_type.clone(), exit_code: exit_code.clone(), stdout: stdout.clone(), stderr: stderr.clone(), duration_ms: duration_ms.clone(), timed_out: timed_out.clone(), timestamp: timestamp.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_log_execution(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("log_execution", callback);
    }
}
