// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateHookArgs {
    pub id: String,
    pub handler_config_json: String,
    pub timeout_secs: u32,
    pub blocking: bool,
    pub tool_pattern: String,
    pub timestamp: String,
}

impl From<UpdateHookArgs> for super::Reducer {
    fn from(args: UpdateHookArgs) -> Self {
        Self::UpdateHook {
            id: args.id,
            handler_config_json: args.handler_config_json,
            timeout_secs: args.timeout_secs,
            blocking: args.blocking,
            tool_pattern: args.tool_pattern,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for UpdateHookArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_hook`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_hook {
    /// Request that the remote module invoke the reducer `update_hook` to run as soon as possible.
    fn update_hook(&self, id: String, handler_config_json: String, timeout_secs: u32, blocking: bool, tool_pattern: String, timestamp: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_hook`.
    fn on_update_hook(&self, callback: impl FnMut(&super::ReducerEventContext, &UpdateHookArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_update_hook(&self, callback: __sdk::CallbackId);
}

impl update_hook for super::RemoteReducers {
    fn update_hook(&self, id: String, handler_config_json: String, timeout_secs: u32, blocking: bool, tool_pattern: String, timestamp: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("update_hook", UpdateHookArgs { id, handler_config_json, timeout_secs, blocking, tool_pattern, timestamp })
    }

    fn on_update_hook(&self, mut callback: impl FnMut(&super::ReducerEventContext, &UpdateHookArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("update_hook", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::UpdateHook { id, handler_config_json, timeout_secs, blocking, tool_pattern, timestamp } = &ctx.event.reducer else { unreachable!() };
            let args = UpdateHookArgs { id: id.clone(), handler_config_json: handler_config_json.clone(), timeout_secs: timeout_secs.clone(), blocking: blocking.clone(), tool_pattern: tool_pattern.clone(), timestamp: timestamp.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_update_hook(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("update_hook", callback);
    }
}
