// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GrantSecretArgs {
    pub agent_id: String,
    pub secret_key: String,
    pub purpose: String,
    pub granted_at: String,
    pub expires_at: String,
}

impl From<GrantSecretArgs> for super::Reducer {
    fn from(args: GrantSecretArgs) -> Self {
        Self::GrantSecret {
            agent_id: args.agent_id,
            secret_key: args.secret_key,
            purpose: args.purpose,
            granted_at: args.granted_at,
            expires_at: args.expires_at,
        }
    }
}

impl __sdk::InModule for GrantSecretArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `grant_secret`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait grant_secret {
    /// Request that the remote module invoke the reducer `grant_secret` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`grant_secret:grant_secret_then`] to run a callback after the reducer completes.
    fn grant_secret(
        &self,
        agent_id: String,
        secret_key: String,
        purpose: String,
        granted_at: String,
        expires_at: String,
    ) -> __sdk::Result<()> {
        self.grant_secret_then(
            agent_id,
            secret_key,
            purpose,
            granted_at,
            expires_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `grant_secret` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn grant_secret_then(
        &self,
        agent_id: String,
        secret_key: String,
        purpose: String,
        granted_at: String,
        expires_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl grant_secret for super::RemoteReducers {
    fn grant_secret_then(
        &self,
        agent_id: String,
        secret_key: String,
        purpose: String,
        granted_at: String,
        expires_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GrantSecretArgs {
                agent_id,
                secret_key,
                purpose,
                granted_at,
                expires_at,
            },
            callback,
        )
    }
}
