// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PruneExpiredArgs {
    pub now: String,
}

impl From<PruneExpiredArgs> for super::Reducer {
    fn from(args: PruneExpiredArgs) -> Self {
        Self::PruneExpired { now: args.now }
    }
}

impl __sdk::InModule for PruneExpiredArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `prune_expired`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait prune_expired {
    /// Request that the remote module invoke the reducer `prune_expired` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`prune_expired:prune_expired_then`] to run a callback after the reducer completes.
    fn prune_expired(&self, now: String) -> __sdk::Result<()> {
        self.prune_expired_then(now, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `prune_expired` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn prune_expired_then(
        &self,
        now: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl prune_expired for super::RemoteReducers {
    fn prune_expired_then(
        &self,
        now: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PruneExpiredArgs { now }, callback)
    }
}
