// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterEndpointArgs {
    pub id: String,
    pub url: String,
    pub provider: String,
    pub model: String,
    pub requires_auth: bool,
    pub secret_key: String,
}

impl From<RegisterEndpointArgs> for super::Reducer {
    fn from(args: RegisterEndpointArgs) -> Self {
        Self::RegisterEndpoint {
            id: args.id,
            url: args.url,
            provider: args.provider,
            model: args.model,
            requires_auth: args.requires_auth,
            secret_key: args.secret_key,
        }
    }
}

impl __sdk::InModule for RegisterEndpointArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_endpoint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_endpoint {
    /// Request that the remote module invoke the reducer `register_endpoint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_endpoint:register_endpoint_then`] to run a callback after the reducer completes.
    fn register_endpoint(
        &self,
        id: String,
        url: String,
        provider: String,
        model: String,
        requires_auth: bool,
        secret_key: String,
    ) -> __sdk::Result<()> {
        self.register_endpoint_then(
            id,
            url,
            provider,
            model,
            requires_auth,
            secret_key,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_endpoint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_endpoint_then(
        &self,
        id: String,
        url: String,
        provider: String,
        model: String,
        requires_auth: bool,
        secret_key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_endpoint for super::RemoteReducers {
    fn register_endpoint_then(
        &self,
        id: String,
        url: String,
        provider: String,
        model: String,
        requires_auth: bool,
        secret_key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterEndpointArgs {
                id,
                url,
                provider,
                model,
                requires_auth,
                secret_key,
            },
            callback,
        )
    }
}
