// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SecretGrant {
    pub id: String,
    pub agent_id: String,
    pub secret_key: String,
    pub purpose: String,
    pub granted_at: String,
    pub expires_at: String,
    pub claimed: bool,
}

impl __sdk::InModule for SecretGrant {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SecretGrant`.
///
/// Provides typed access to columns for query building.
pub struct SecretGrantCols {
    pub id: __sdk::__query_builder::Col<SecretGrant, String>,
    pub agent_id: __sdk::__query_builder::Col<SecretGrant, String>,
    pub secret_key: __sdk::__query_builder::Col<SecretGrant, String>,
    pub purpose: __sdk::__query_builder::Col<SecretGrant, String>,
    pub granted_at: __sdk::__query_builder::Col<SecretGrant, String>,
    pub expires_at: __sdk::__query_builder::Col<SecretGrant, String>,
    pub claimed: __sdk::__query_builder::Col<SecretGrant, bool>,
}

impl __sdk::__query_builder::HasCols for SecretGrant {
    type Cols = SecretGrantCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SecretGrantCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            secret_key: __sdk::__query_builder::Col::new(table_name, "secret_key"),
            purpose: __sdk::__query_builder::Col::new(table_name, "purpose"),
            granted_at: __sdk::__query_builder::Col::new(table_name, "granted_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            claimed: __sdk::__query_builder::Col::new(table_name, "claimed"),
        }
    }
}

/// Indexed column accessor struct for the table `SecretGrant`.
///
/// Provides typed access to indexed columns for query building.
pub struct SecretGrantIxCols {
    pub id: __sdk::__query_builder::IxCol<SecretGrant, String>,
}

impl __sdk::__query_builder::HasIxCols for SecretGrant {
    type IxCols = SecretGrantIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SecretGrantIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SecretGrant {}
