// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearConversationArgs {
    pub conversation_id: String,
}

impl From<ClearConversationArgs> for super::Reducer {
    fn from(args: ClearConversationArgs) -> Self {
        Self::ClearConversation {
            conversation_id: args.conversation_id,
        }
    }
}

impl __sdk::InModule for ClearConversationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_conversation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_conversation {
    /// Request that the remote module invoke the reducer `clear_conversation` to run as soon as possible.
    fn clear_conversation(&self, conversation_id: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `clear_conversation`.
    fn on_clear_conversation(&self, callback: impl FnMut(&super::ReducerEventContext, &ClearConversationArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_clear_conversation(&self, callback: __sdk::CallbackId);
}

impl clear_conversation for super::RemoteReducers {
    fn clear_conversation(&self, conversation_id: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("clear_conversation", ClearConversationArgs { conversation_id })
    }

    fn on_clear_conversation(&self, mut callback: impl FnMut(&super::ReducerEventContext, &ClearConversationArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("clear_conversation", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::ClearConversation { conversation_id } = &ctx.event.reducer else { unreachable!() };
            let args = ClearConversationArgs { conversation_id: conversation_id.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_clear_conversation(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("clear_conversation", callback);
    }
}
