// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Conversation {
    pub id: String,
    pub created_at: String,
    pub agent_id: String,
}

impl __sdk::InModule for Conversation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Conversation`.
///
/// Provides typed access to columns for query building.
pub struct ConversationCols {
    pub id: __sdk::__query_builder::Col<Conversation, String>,
    pub created_at: __sdk::__query_builder::Col<Conversation, String>,
    pub agent_id: __sdk::__query_builder::Col<Conversation, String>,
}

impl __sdk::__query_builder::HasCols for Conversation {
    type Cols = ConversationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConversationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Conversation`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConversationIxCols {
    pub id: __sdk::__query_builder::IxCol<Conversation, String>,
}

impl __sdk::__query_builder::HasIxCols for Conversation {
    type IxCols = ConversationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConversationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

