// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateConversationArgs {
    pub id: String,
    pub agent_id: String,
}

impl From<CreateConversationArgs> for super::Reducer {
    fn from(args: CreateConversationArgs) -> Self {
        Self::CreateConversation {
            id: args.id,
            agent_id: args.agent_id,
        }
    }
}

impl __sdk::InModule for CreateConversationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_conversation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_conversation {
    /// Request that the remote module invoke the reducer `create_conversation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_conversation:create_conversation_then`] to run a callback after the reducer completes.
    fn create_conversation(&self, id: String, agent_id: String) -> __sdk::Result<()> {
        self.create_conversation_then(id, agent_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_conversation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_conversation_then(
        &self,
        id: String,
        agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_conversation for super::RemoteReducers {
    fn create_conversation_then(
        &self,
        id: String,
        agent_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateConversationArgs { id, agent_id }, callback)
    }
}
