// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendMessageArgs {
    pub conversation_id: String,
    pub role: String,
    pub content: String,
}

impl From<SendMessageArgs> for super::Reducer {
    fn from(args: SendMessageArgs) -> Self {
        Self::SendMessage {
            conversation_id: args.conversation_id,
            role: args.role,
            content: args.content,
        }
    }
}

impl __sdk::InModule for SendMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_message {
    /// Request that the remote module invoke the reducer `send_message` to run as soon as possible.
    fn send_message(&self, conversation_id: String, role: String, content: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_message`.
    fn on_send_message(&self, callback: impl FnMut(&super::ReducerEventContext, &SendMessageArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_send_message(&self, callback: __sdk::CallbackId);
}

impl send_message for super::RemoteReducers {
    fn send_message(&self, conversation_id: String, role: String, content: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("send_message", SendMessageArgs { conversation_id, role, content })
    }

    fn on_send_message(&self, mut callback: impl FnMut(&super::ReducerEventContext, &SendMessageArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("send_message", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::SendMessage { conversation_id, role, content } = &ctx.event.reducer else { unreachable!() };
            let args = SendMessageArgs { conversation_id: conversation_id.clone(), role: role.clone(), content: content.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_send_message(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("send_message", callback);
    }
}
