#!/usr/bin/env bash
# setup-cargo-fast.sh — Apply ADR-064 Rust compilation performance optimizations
# See docs/adrs/ADR-064-rust-compilation-performance.md
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CARGO_CONFIG="$REPO_ROOT/.cargo/config.toml"
WORKSPACE_CARGO="$REPO_ROOT/Cargo.toml"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
fail() { echo -e "${RED}✗${NC} $*"; }
step() { echo -e "\n⬡ $*"; }

HAS_LLD=false
HAS_SCCACHE=false
HAS_NEXTEST=false

# ── Step 1: Install fast linker (lld via LLVM) ────────────────────────────────
step "Checking fast linker (lld)..."

# Check standalone lld formula first, then llvm formula
LLD_PATH=""
for candidate in \
    "/opt/homebrew/opt/lld/bin/ld64.lld" \
    "/opt/homebrew/opt/llvm/bin/ld64.lld"; do
    if [[ -f "$candidate" ]]; then
        LLD_PATH="$candidate"
        break
    fi
done

if [[ -n "$LLD_PATH" ]]; then
    ok "lld already installed at $LLD_PATH"
    HAS_LLD=true
elif command -v brew &>/dev/null; then
    warn "lld not found — installing via brew..."
    brew install lld
    # Re-check after install
    for candidate in \
        "/opt/homebrew/opt/lld/bin/ld64.lld" \
        "/opt/homebrew/opt/llvm/bin/ld64.lld"; do
        if [[ -f "$candidate" ]]; then
            LLD_PATH="$candidate"
            break
        fi
    done
    if [[ -n "$LLD_PATH" ]]; then
        ok "lld installed at $LLD_PATH"
        HAS_LLD=true
    else
        fail "lld not found at expected path after install"
    fi
else
    warn "brew not available — skipping lld (linker will remain default)"
fi

# ── Step 2: Install sccache ───────────────────────────────────────────────────
step "Checking sccache..."

if command -v sccache &>/dev/null; then
    ok "sccache already installed: $(sccache --version 2>&1 | head -1)"
    HAS_SCCACHE=true
elif command -v brew &>/dev/null; then
    warn "sccache not found — installing via brew..."
    brew install sccache
    if command -v sccache &>/dev/null; then
        ok "sccache installed: $(sccache --version 2>&1 | head -1)"
        HAS_SCCACHE=true
    else
        fail "sccache install failed"
    fi
elif command -v cargo &>/dev/null; then
    warn "brew not available — installing sccache via cargo install..."
    cargo install sccache --locked
    HAS_SCCACHE=true
    ok "sccache installed via cargo"
else
    warn "Cannot install sccache — skipping"
fi

# ── Step 3: Install cargo-nextest ─────────────────────────────────────────────
step "Checking cargo-nextest..."

if command -v cargo-nextest &>/dev/null || cargo nextest --version &>/dev/null 2>&1; then
    ok "cargo-nextest already installed"
    HAS_NEXTEST=true
elif command -v brew &>/dev/null; then
    warn "cargo-nextest not found — installing via brew..."
    brew install cargo-nextest 2>/dev/null || {
        warn "brew tap needed — trying cargo install..."
        cargo install cargo-nextest --locked
    }
    HAS_NEXTEST=true
    ok "cargo-nextest installed"
elif command -v cargo &>/dev/null; then
    warn "Installing cargo-nextest via cargo install..."
    cargo install cargo-nextest --locked
    HAS_NEXTEST=true
    ok "cargo-nextest installed"
else
    warn "Cannot install cargo-nextest — skipping"
fi

# ── Step 4: Write .cargo/config.toml ─────────────────────────────────────────
step "Writing $CARGO_CONFIG..."

mkdir -p "$REPO_ROOT/.cargo"

SCCACHE_LINE=""
if $HAS_SCCACHE; then
    SCCACHE_LINE='rustc-wrapper = "sccache"   # cross-build crate caching (ADR-064)'
else
    SCCACHE_LINE='# rustc-wrapper = "sccache" # Uncomment after: brew install sccache'
fi

if $HAS_LLD; then
    LINKER_BLOCK="[target.aarch64-apple-darwin]
linker = \"clang\"
rustflags = [\"-C\", \"link-arg=-fuse-ld=$LLD_PATH\"]
"
else
    LINKER_BLOCK='# [target.aarch64-apple-darwin]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=<lld-path>"]
# Uncomment after: brew install lld
'
fi

cat > "$CARGO_CONFIG" << EOF
# ADR-064: Rust compilation performance
# See docs/adrs/ADR-064-rust-compilation-performance.md
# Generated by scripts/setup-cargo-fast.sh

[build]
jobs = 12                    # saturate all cores (Apple M2 Max / 12 cores)
$SCCACHE_LINE

$LINKER_BLOCK
EOF

ok "Written: $CARGO_CONFIG"

# ── Step 5: Add dev profile to workspace Cargo.toml if missing ───────────────
step "Checking workspace Cargo.toml for dev profile..."

if grep -q '\[profile\.dev\]' "$WORKSPACE_CARGO"; then
    ok "dev profile already present in Cargo.toml"
else
    warn "Adding dev profile optimizations to Cargo.toml..."
    cat >> "$WORKSPACE_CARGO" << 'EOF'

[profile.dev]
opt-level = 0
debug = 1                   # line tables only (not full debug info) — cuts link time

[profile.dev.package."*"]
opt-level = 3               # optimize dependencies at max, keep our code fast-to-compile
EOF
    ok "dev profile added to $WORKSPACE_CARGO"
fi

# ── Step 6: Verify ────────────────────────────────────────────────────────────
step "Verifying setup..."

echo ""
echo "  Configuration: $CARGO_CONFIG"
cat "$CARGO_CONFIG" | sed 's/^/    /'
echo ""

if $HAS_SCCACHE; then
    echo "  sccache stats:"
    sccache --show-stats 2>&1 | grep -E "^(Compile|Cache|Successful|Could not)" | sed 's/^/    /' || true
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
ok "Setup complete. Expected improvements (ADR-064):"
echo ""
$HAS_LLD    && echo "  ✓ lld linker       → 30-50% faster link phase ($LLD_PATH)" || warn "  - lld linker       → not installed (install: brew install lld)"
$HAS_SCCACHE && echo "  ✓ sccache          → near-instant rebuilds on branch/worktree switch" || warn "  - sccache          → not installed (install: brew install sccache)"
$HAS_NEXTEST && echo "  ✓ cargo-nextest    → parallel test execution (replaces cargo test)" || warn "  - cargo-nextest    → not installed"
echo "  ✓ dev profile      → opt deps at 3, your code at 0"
echo ""
echo "  TIP: Use debug builds during development:"
echo "       cargo build -p hex-cli          (not --release)"
echo "       cargo build -p hex-nexus        (not --release)"
$HAS_NEXTEST && echo "       cargo nextest run               (replaces cargo test)"
echo ""
