#!/usr/bin/env bash
# Start script for Hello CLI Implementation
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Building..."
cargo build --release

echo "Starting application..."
./target/release/$(basename $(pwd))
