// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_definition_version_type::AgentDefinitionVersion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_definition_version`.
///
/// Obtain a handle from the [`AgentDefinitionVersionTableAccess::agent_definition_version`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_definition_version()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_definition_version().on_insert(...)`.
pub struct AgentDefinitionVersionTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentDefinitionVersion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_definition_version`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentDefinitionVersionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentDefinitionVersionTableHandle`], which mediates access to the table `agent_definition_version`.
    fn agent_definition_version(&self) -> AgentDefinitionVersionTableHandle<'_>;
}

impl AgentDefinitionVersionTableAccess for super::RemoteTables {
    fn agent_definition_version(&self) -> AgentDefinitionVersionTableHandle<'_> {
        AgentDefinitionVersionTableHandle {
            imp: self
                .imp
                .get_table::<AgentDefinitionVersion>("agent_definition_version"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentDefinitionVersionInsertCallbackId(__sdk::CallbackId);
pub struct AgentDefinitionVersionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentDefinitionVersionTableHandle<'ctx> {
    type Row = AgentDefinitionVersion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentDefinitionVersion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentDefinitionVersionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentDefinitionVersionInsertCallbackId {
        AgentDefinitionVersionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentDefinitionVersionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentDefinitionVersionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentDefinitionVersionDeleteCallbackId {
        AgentDefinitionVersionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentDefinitionVersionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<AgentDefinitionVersion>("agent_definition_version");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AgentDefinitionVersion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentDefinitionVersion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentDefinitionVersion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_definition_versionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentDefinitionVersion`.
    fn agent_definition_version(&self) -> __sdk::__query_builder::Table<AgentDefinitionVersion>;
}

impl agent_definition_versionQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_definition_version(&self) -> __sdk::__query_builder::Table<AgentDefinitionVersion> {
        __sdk::__query_builder::Table::new("agent_definition_version")
    }
}
