// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_definition_type::AgentDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_definition`.
///
/// Obtain a handle from the [`AgentDefinitionTableAccess::agent_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_definition().on_insert(...)`.
pub struct AgentDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentDefinitionTableHandle`], which mediates access to the table `agent_definition`.
    fn agent_definition(&self) -> AgentDefinitionTableHandle<'_>;
}

impl AgentDefinitionTableAccess for super::RemoteTables {
    fn agent_definition(&self) -> AgentDefinitionTableHandle<'_> {
        AgentDefinitionTableHandle {
            imp: self.imp.get_table::<AgentDefinition>("agent_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct AgentDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentDefinitionTableHandle<'ctx> {
    type Row = AgentDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentDefinitionInsertCallbackId {
        AgentDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentDefinitionDeleteCallbackId {
        AgentDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

/// Access to the `id` unique index on the table `agent_definition`,
/// which allows point queries on the field of the same name
/// via the [`AgentDefinitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_definition().id().find(...)`.
pub struct AgentDefinitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentDefinition, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentDefinitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `agent_definition`.
    pub fn id(&self) -> AgentDefinitionIdUnique<'ctx> {
        AgentDefinitionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentDefinitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgentDefinition> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `agent_definition`,
/// which allows point queries on the field of the same name
/// via the [`AgentDefinitionNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_definition().name().find(...)`.
pub struct AgentDefinitionNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentDefinition, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentDefinitionTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `agent_definition`.
    pub fn name(&self) -> AgentDefinitionNameUnique<'ctx> {
        AgentDefinitionNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentDefinitionNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgentDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentDefinition>("agent_definition");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AgentDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentDefinition`.
    fn agent_definition(&self) -> __sdk::__query_builder::Table<AgentDefinition>;
}

impl agent_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_definition(&self) -> __sdk::__query_builder::Table<AgentDefinition> {
        __sdk::__query_builder::Table::new("agent_definition")
    }
}
