// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentDefinitionVersion {
    pub definition_id: String,
    pub version: u32,
    pub snapshot_json: String,
    pub created_at: String,
}

impl __sdk::InModule for AgentDefinitionVersion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentDefinitionVersion`.
///
/// Provides typed access to columns for query building.
pub struct AgentDefinitionVersionCols {
    pub definition_id: __sdk::__query_builder::Col<AgentDefinitionVersion, String>,
    pub version: __sdk::__query_builder::Col<AgentDefinitionVersion, u32>,
    pub snapshot_json: __sdk::__query_builder::Col<AgentDefinitionVersion, String>,
    pub created_at: __sdk::__query_builder::Col<AgentDefinitionVersion, String>,
}

impl __sdk::__query_builder::HasCols for AgentDefinitionVersion {
    type Cols = AgentDefinitionVersionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentDefinitionVersionCols {
            definition_id: __sdk::__query_builder::Col::new(table_name, "definition_id"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            snapshot_json: __sdk::__query_builder::Col::new(table_name, "snapshot_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentDefinitionVersion`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentDefinitionVersionIxCols {}

impl __sdk::__query_builder::HasIxCols for AgentDefinitionVersion {
    type IxCols = AgentDefinitionVersionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentDefinitionVersionIxCols {}
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentDefinitionVersion {}
