// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetDefinitionByNameArgs {
    pub name: String,
}

impl From<GetDefinitionByNameArgs> for super::Reducer {
    fn from(args: GetDefinitionByNameArgs) -> Self {
        Self::GetDefinitionByName { name: args.name }
    }
}

impl __sdk::InModule for GetDefinitionByNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_definition_by_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_definition_by_name {
    /// Request that the remote module invoke the reducer `get_definition_by_name` to run as soon as possible.
    fn get_definition_by_name(&self, name: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `get_definition_by_name`.
    fn on_get_definition_by_name(&self, callback: impl FnMut(&super::ReducerEventContext, &GetDefinitionByNameArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_get_definition_by_name(&self, callback: __sdk::CallbackId);
}

impl get_definition_by_name for super::RemoteReducers {
    fn get_definition_by_name(&self, name: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("get_definition_by_name", GetDefinitionByNameArgs { name })
    }

    fn on_get_definition_by_name(&self, mut callback: impl FnMut(&super::ReducerEventContext, &GetDefinitionByNameArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("get_definition_by_name", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::GetDefinitionByName { name } = &ctx.event.reducer else { unreachable!() };
            let args = GetDefinitionByNameArgs { name: name.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_get_definition_by_name(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("get_definition_by_name", callback);
    }
}
