// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterDefinitionArgs {
    pub id: String,
    pub name: String,
    pub description: String,
    pub role_prompt: String,
    pub allowed_tools_json: String,
    pub constraints_json: String,
    pub model: String,
    pub max_turns: u32,
    pub metadata_json: String,
    pub timestamp: String,
}

impl From<RegisterDefinitionArgs> for super::Reducer {
    fn from(args: RegisterDefinitionArgs) -> Self {
        Self::RegisterDefinition {
            id: args.id,
            name: args.name,
            description: args.description,
            role_prompt: args.role_prompt,
            allowed_tools_json: args.allowed_tools_json,
            constraints_json: args.constraints_json,
            model: args.model,
            max_turns: args.max_turns,
            metadata_json: args.metadata_json,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for RegisterDefinitionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_definition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_definition {
    /// Request that the remote module invoke the reducer `register_definition` to run as soon as possible.
    fn register_definition(&self, id: String, name: String, description: String, role_prompt: String, allowed_tools_json: String, constraints_json: String, model: String, max_turns: u32, metadata_json: String, timestamp: String,) -> __sdk::Result<()>;

    /// Register a callback to run whenever we are notified of an invocation of the reducer `register_definition`.
    fn on_register_definition(&self, callback: impl FnMut(&super::ReducerEventContext, &RegisterDefinitionArgs) + Send + 'static) -> __sdk::CallbackId;

    /// Unregister a previously-registered callback.
    fn remove_on_register_definition(&self, callback: __sdk::CallbackId);
}

impl register_definition for super::RemoteReducers {
    fn register_definition(&self, id: String, name: String, description: String, role_prompt: String, allowed_tools_json: String, constraints_json: String, model: String, max_turns: u32, metadata_json: String, timestamp: String,) -> __sdk::Result<()> {
        self.imp.call_reducer("register_definition", RegisterDefinitionArgs { id, name, description, role_prompt, allowed_tools_json, constraints_json, model, max_turns, metadata_json, timestamp })
    }

    fn on_register_definition(&self, mut callback: impl FnMut(&super::ReducerEventContext, &RegisterDefinitionArgs) + Send + 'static) -> __sdk::CallbackId {
        self.imp.on_reducer("register_definition", Box::new(move |ctx: &super::ReducerEventContext| {
            let super::Reducer::RegisterDefinition { id, name, description, role_prompt, allowed_tools_json, constraints_json, model, max_turns, metadata_json, timestamp } = &ctx.event.reducer else { unreachable!() };
            let args = RegisterDefinitionArgs { id: id.clone(), name: name.clone(), description: description.clone(), role_prompt: role_prompt.clone(), allowed_tools_json: allowed_tools_json.clone(), constraints_json: constraints_json.clone(), model: model.clone(), max_turns: max_turns.clone(), metadata_json: metadata_json.clone(), timestamp: timestamp.clone() };
            callback(ctx, &args);
        }))
    }

    fn remove_on_register_definition(&self, callback: __sdk::CallbackId) {
        self.imp.remove_on_reducer("register_definition", callback);
    }
}
