#!/usr/bin/env bash
# Start script for Plan: P4.1: Implement composition root with React integration
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
