#!/usr/bin/env bash
# Start script for Plan: build a todo list REST API in rust with axum
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Building..."
cargo build --release

echo "Starting application..."
./target/release/$(basename $(pwd))
