// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InferenceEndpoint {
    pub id: String,
    pub url: String,
    pub provider: String,
    pub model: String,
    pub status: String,
    pub requires_auth: bool,
    pub secret_key: String,
    pub health_checked_at: String,
}

impl __sdk::InModule for InferenceEndpoint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InferenceEndpoint`.
///
/// Provides typed access to columns for query building.
pub struct InferenceEndpointCols {
    pub id: __sdk::__query_builder::Col<InferenceEndpoint, String>,
    pub url: __sdk::__query_builder::Col<InferenceEndpoint, String>,
    pub provider: __sdk::__query_builder::Col<InferenceEndpoint, String>,
    pub model: __sdk::__query_builder::Col<InferenceEndpoint, String>,
    pub status: __sdk::__query_builder::Col<InferenceEndpoint, String>,
    pub requires_auth: __sdk::__query_builder::Col<InferenceEndpoint, bool>,
    pub secret_key: __sdk::__query_builder::Col<InferenceEndpoint, String>,
    pub health_checked_at: __sdk::__query_builder::Col<InferenceEndpoint, String>,
}

impl __sdk::__query_builder::HasCols for InferenceEndpoint {
    type Cols = InferenceEndpointCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InferenceEndpointCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            url: __sdk::__query_builder::Col::new(table_name, "url"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            model: __sdk::__query_builder::Col::new(table_name, "model"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            requires_auth: __sdk::__query_builder::Col::new(table_name, "requires_auth"),
            secret_key: __sdk::__query_builder::Col::new(table_name, "secret_key"),
            health_checked_at: __sdk::__query_builder::Col::new(table_name, "health_checked_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InferenceEndpoint`.
///
/// Provides typed access to indexed columns for query building.
pub struct InferenceEndpointIxCols {
    pub id: __sdk::__query_builder::IxCol<InferenceEndpoint, String>,
}

impl __sdk::__query_builder::HasIxCols for InferenceEndpoint {
    type IxCols = InferenceEndpointIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InferenceEndpointIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InferenceEndpoint {}
