#!/usr/bin/env bash
# Start script for Plan: P3.1: Create DriverStatsUseCase in usecases/
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
