#!/usr/bin/env bash
# Start script for Plan: P5.1: Implement integration tests for driver standings flow (API + React)
# Generated by hex dev

set -euo pipefail
cd "$(dirname "$0")"

echo "Installing dependencies..."
npm install

echo "Building..."
npx tsc

echo "Starting application..."
node dist/main.js
