// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateDefinitionArgs {
    pub id: String,
    pub description: String,
    pub role_prompt: String,
    pub allowed_tools_json: String,
    pub constraints_json: String,
    pub model: String,
    pub max_turns: u32,
    pub metadata_json: String,
    pub timestamp: String,
}

impl From<UpdateDefinitionArgs> for super::Reducer {
    fn from(args: UpdateDefinitionArgs) -> Self {
        Self::UpdateDefinition {
            id: args.id,
            description: args.description,
            role_prompt: args.role_prompt,
            allowed_tools_json: args.allowed_tools_json,
            constraints_json: args.constraints_json,
            model: args.model,
            max_turns: args.max_turns,
            metadata_json: args.metadata_json,
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for UpdateDefinitionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_definition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_definition {
    /// Request that the remote module invoke the reducer `update_definition` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_definition:update_definition_then`] to run a callback after the reducer completes.
    fn update_definition(
        &self,
        id: String,
        description: String,
        role_prompt: String,
        allowed_tools_json: String,
        constraints_json: String,
        model: String,
        max_turns: u32,
        metadata_json: String,
        timestamp: String,
    ) -> __sdk::Result<()> {
        self.update_definition_then(
            id,
            description,
            role_prompt,
            allowed_tools_json,
            constraints_json,
            model,
            max_turns,
            metadata_json,
            timestamp,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_definition` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_definition_then(
        &self,
        id: String,
        description: String,
        role_prompt: String,
        allowed_tools_json: String,
        constraints_json: String,
        model: String,
        max_turns: u32,
        metadata_json: String,
        timestamp: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_definition for super::RemoteReducers {
    fn update_definition_then(
        &self,
        id: String,
        description: String,
        role_prompt: String,
        allowed_tools_json: String,
        constraints_json: String,
        model: String,
        max_turns: u32,
        metadata_json: String,
        timestamp: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateDefinitionArgs {
                id,
                description,
                role_prompt,
                allowed_tools_json,
                constraints_json,
                model,
                max_turns,
                metadata_json,
                timestamp,
            },
            callback,
        )
    }
}
