import { createMemo, For, Show } from 'solid-js'; interface AttentionItem { id: string; priority: 0 | 1 | 2; kind: 'escalation' | 'overdue_commitment' | 'merge_vote_needed' | 'resource_anomaly' | 'autonomous_commit' | 'agent_run_active'; title: string; subtitle: string; age_seconds: number; action_url?: string; cli_repro?: string; } interface AttentionFeedProps { items: AttentionItem[]; } function formatAge(s: number): string { if (s < 60) return s + 's ago'; if (s < 3600) return Math.floor(s/60) + 'm ago'; if (s < 86400) return Math.floor(s/3600) + 'h ago'; return Math.floor(s/86400) + 'd ago'; } function kindGlyph(k: AttentionItem['kind']): string { switch (k) { case 'escalation': return '!'; case 'overdue_commitment': return 'O'; case 'merge_vote_needed': return 'M'; case 'resource_anomaly': return '*'; case 'autonomous_commit': return '+'; case 'agent_run_active': return '>'; default: return '.'; } } export default function AttentionFeed(props: AttentionFeedProps) { const sorted = createMemo(() => [...props.items].sort((a, b) => a.priority - b.priority || b.age_seconds - a.age_seconds)); const pillClass = (p: 0|1|2) => p === 0 ? 'bg-red-600 text-white' : p === 1 ? 'bg-amber-500 text-white' : 'bg-blue-500 text-white'; return (<div class='space-y-3'><For each={sorted()}>{(item) => (<div class='rounded border border-zinc-700 bg-zinc-900 p-3'><div class='flex items-center gap-2 text-xs'><span class='text-zinc-300 font-mono mr-1'>{kindGlyph(item.kind)}</span><span class={pillClass(item.priority) + ' px-2 py-0.5 rounded'}>P{item.priority}</span><span class='text-zinc-400 uppercase tracking-wide'>{item.kind}</span><span class='text-zinc-500 ml-auto'>{formatAge(item.age_seconds)}</span></div><h3 class='text-sm font-semibold text-zinc-100 mt-1'>{item.title}</h3><p class='text-xs text-zinc-400'>{item.subtitle}</p><div class='flex items-center gap-2 text-xs mt-1'><Show when={item.action_url}><a href={item.action_url} class='text-cyan-400 hover:underline'>Inspect</a></Show><Show when={item.cli_repro}><button class='px-2 py-0.5 rounded bg-zinc-800 text-zinc-300 hover:[PERSON_NAME] onClick={() => navigator.clipboard.writeText(item.cli_repro!)}>Copy CLI</button></Show></div></div>)}</For></div>); }

interface AttentionItem { id: string; priority: 0 | 1 | 2; kind: 'escalation' | 'overdue_commitment' | 'merge_vote_needed' | 'resource_anomaly' | 'autonomous_commit' | 'agent_run_active'; title: string; subtitle: string; age_seconds: number; action_url?: string; cli_repro?: string; }

interface AttentionFeedProps { items: AttentionItem[]; }

function formatAge(s: number): string { if (s < 60) return s + 's ago'; if (s < 3600) return Math.floor(s/60) + 'm ago'; if (s < 86400) return Math.floor(s/3600) + 'h ago'; return Math.floor(s/86400) + 'd ago'; }

export default function AttentionFeed(props: AttentionFeedProps) { const sorted = createMemo(() => [...props.items].sort((a, b) => a.priority - b.priority || b.age_seconds - a.age_seconds)); const pillClass = (p: 0|1|2) => p === 0 ? 'bg-red-600 text-white' : p === 1 ? 'bg-amber-500 text-white' : 'bg-blue-500 text-white'; return (<div class='space-y-3'><For each={sorted()}>{(item) => (<div class='rounded border border-zinc-700 bg-zinc-900 p-3'><div class='flex items-center gap-2 text-xs'><span class={pillClass(item.priority) + ' px-2 py-0.5 rounded'}>P{item.priority}</span><span class='text-zinc-400 uppercase tracking-wide'>{item.kind}</span><span class='text-zinc-500 ml-auto'>{formatAge(item.age_seconds)}</span></div><h3 class='text-sm font-semibold text-zinc-100 mt-1'>{item.title}</h3><p class='text-xs text-zinc-400'>{item.subtitle}</p><div class='flex items-center gap-2 text-xs mt-1'><Show when={item.action_url}><a href={item.action_url} class='text-cyan-400 hover:underline'>Inspect</a></Show><Show when={item.cli_repro}><button class='px-2 py-0.5 rounded bg-zinc-800 text-zinc-300 hover:bg-zinc-700' onClick={() => navigator.clipboard.writeText(item.cli_repro!)}>Copy CLI</button></Show></div></div>)}</For></div>); }
